### ISSUE TITLE
[1.12.2] Players timing out when entering Nether

### ISSUE THREAD

**Issue by randomlypickedname** [TeamJM/journeymap#42] opened 2018-05-04 05:34 UTC
#### JourneyMap Version:

1.12.2-5.5.2

#### Forge Version:

1.12.2-14.23.3.2673

#### Describe the problem in repeatable steps:

1. Whenever a player enters the Nether, an error appears in the server console involving 'Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission' and the server times out.

Our latest.log: https://gist.github.com/randomlypickedname/9d44fefb2d60cfdd0f867d74a1dfcb93

**Comment by ren-** [comment] 2018-05-05 05:13
Similar problem here:

https://gist.github.com/ren-/1ef44c588d0c56abb52c9046df1bebba

But the client timeouts. When I send the message to chat, the server gets it instantly, yet the client doesn't even receive its own message and eventually timeouts.

**Comment by Yoosk** [comment] 2018-05-18 20:40
Looks like similiar one:
https://gist.github.com/2c9d9a12f3769e2a67175a5a346c14df

**Comment by thiakil** [comment] 2018-05-19 01:51
I don't think it's restricted to the nether as the title implies; I get it for all my players on login

```
[09:46:19] [Server thread/INFO] [journeymap]: <player> joining dimension 0
[09:46:19] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
        at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
        at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
```

**Comment by danny50610** [comment] 2018-05-22 14:13
Perhaps it's because of the following PR has been merged to Forge
https://github.com/MinecraftForge/MinecraftForge/pull/4890

Maybe this bug can be solved if DimensionPermissionPacket is registered both on the server side and client side

**Comment by RJ-Fynydd** [comment] 2018-05-23 21:35
Has anyone found a way around this? I have a player on my server who is just locked out.

**Comment by ren-** [comment] 2018-05-23 22:20
For me, the timeout stops if I use a VPN to alter my route to the server.

**Comment by thiakil** [comment] 2018-05-28 01:01
Seriously, @BrainStone @techbrew-mc how has this not been fixed already?

The simple fix would be to remove the `if(Side.CLIENT == side)` from the `DIMENSION_PERMISSIONS_CHANNEL.registerMessage` call.

That said, that is your packet handler is in need of some **major** attention. You should only need *one* channel.

**Comment by robvaivodiss** [comment] 2018-05-31 02:29
Having a similar issue on Forge 2705 on 1.12.2. When player enters Nether the game lags and then server skips a bunch of ticks and does the Undefined Discriminator message. Impossible to play with this lag.
[](https://pastebin.com/cS8qg6Nb)

**Comment by smmmadden** [comment] 2018-05-31 17:28
The problem isn't because of using one or more channels (at least not for my scenario).  Using Forge 2705 for Minecraft 1.12.2, my server was using JourneyMap-1.12.2-5.5.2.jar and my client was using journeymap-1.12.2-5.6.0b2.jar which didn't match.  Once I updated the server to the same versioned jar, everything is happier now with no exceptions.  I suspect this is the case for others too. -Steve

**Comment by Yoosk** [comment] 2018-05-31 17:37
But there is no 1.12.2-5.6.0b2.jar on curse so i cant really force update for that.

**Comment by smmmadden** [comment] 2018-05-31 17:50
I just checked again and there are docs that talk about this build and I did download at one point, just not finding the download link for it now.  Are both your server and clients using the same?  I can think of scenarios where the player downloaded (or still has) an older version of JM but the server has the newer version and they don't match.  Could this be the case for you too?

**Comment by LemADEC** [comment] 2018-05-31 20:38
Issue is reproduced with 1.12.2-5.5.2 on both client and server side

**Comment by Hillage** [comment] 2018-05-31 21:20
We have the same:

Journeymap 1.12.2-5.5.2 on client and server. Stock config on server.
Forge version was updated to forge-1.12.2-14.23.4.2703 on client and server.

We are going to try removing JM from the server side later, as I am under the impression that it is not needed server-side if the server is not utilizing specific config (eg. blocking specific features)

**Comment by Hillage** [comment] 2018-05-31 21:33
Confirming that disabling/removing journeymap from the server side has stopped the log spam. Note that we didn't appear to have any lag when this spam occurred, however we do have beefy server specs.

This only works because we don't restrict any features on the server side. For those that do, unfortunately a different solution needs to be found.

**Comment by robvaivodiss** [comment] 2018-06-01 00:30
Here is an update on my issue. I removed Journeymap on the server side and the log spam and errors are gone. As a note, I had the same version of Journeymap installed on the client. 
As before, visiting the nether causes insane lag. Here is a log of the TPS:
[https://pastebin.com/QTiUWpSp](https://pastebin.com/QTiUWpSp)

I also tried removing Journeymap from the client and it still has the same lag issue.

**Comment by smmmadden** [comment] 2018-06-01 01:34
confirmed - removing it from the server mods folder did the trick.  Must have been some change in forge or sponge that's causing it as it was fine on my last build of Forge 2655 / Sponge 3052.  At least we have a workaround for now to stop the noise.  Thanks.

**Comment by skittersmurf** [comment] 2018-06-05 13:11
Did the same on my end. ROBVAIVODISS thank you for coming up with a fix and SMMMADDEN thank you for confirming, this was driving me nuts trying to find our what was going on, dug through all the configs for a couple days...

**Comment by Weissmoon** [comment] 2018-06-07 11:53
This is because the packet sending is not the same as the packet registered.
I did the same mistake.

**Comment by Sanofus** [comment] 2018-06-10 09:42
@Yoosk The 1.12.2-5.6.0b2.jar has been removed for unknown reason from curseforge.

**Comment by BrainStone** [comment] 2018-06-10 10:40
It has been removed because it was too unstable and both devs didn't have time to continue working on it at that time.

**Comment by mysticdrew** [comment] 2018-06-11 16:59
use the version of forge that journeymap was built on if you need the server features to work. That is the only workaround for now. I don't have permission on curse to upload an updated version. I also have not had time to make a fix for it.

**Comment by Weissmoon** [comment] 2018-07-04 21:07
This is a simple fix.
The class registered in your Network Wrapper is not the same that you are instancing to send to the client. The classes need to be the exact same classes.

The class here:
        INSTANCE.registerMessage(Packet1Handler.class, Packet1.class, 0, Side.CLIENT);

needs to be the same class here:
                ServerNetworkHandler.INSTANCE.sendTo(INSTANCE.packet, Packet1);

If the classes are not the same, the Network Wrapper assumes the packet is invalid and discards it.
This is due to a change in Forge 14.23.3.2672. You can read it MinecraftForge/MinecraftForge#4890 for info on the change.

**Comment by OronDF343** [comment] 2018-07-09 18:57
How exactly is this critical issue not fixed yet 3 months later? A player on my server can't log in at all due to this issue

**Comment by mysticdrew** [comment] 2018-07-09 19:04
Because both developers have real life. Development is on hold currently. 
Remove JM from your server and then you will not have problems.

**Comment by Wissi** [comment] 2018-07-13 08:01
Why close this Issue if it's not fixed?
Still happens and no new updated version has been made?

Is there a workaround other than removing, not having JM at all while on server?
Is there any news?

**Comment by Weissmoon** [comment] 2018-07-19 16:34
I fixed it with [this](https://minecraft.curseforge.com/projects/journeymapfixer/files/2586654).

**Comment by CarsonF** [comment] 2018-08-07 04:09
@Weissmoon would you mind PRing this? You seem to understand the code changes necessary. I'm sure the devs would be grateful.

**Comment by mysticdrew** [comment] 2018-08-07 14:53
A PR will do no good since we are not open sourced. This fix will be fixed when forge for 1.13 recommended build comes out. I will be porting JM to 1.13 applying bug fixes, then merging those fixes to 1.12.2. I will not do it before then, my time is very limited. There are not enough hours in the day to do work that does not have a paycheck. 

Current solutions:
Don't put JM on your server. 
Use any forge below forge-1.12.2-14.23.4.2703. 
Use @Weissmoon's fix.

**Comment by thiakil** [comment] 2018-08-08 00:01
@mysticdrew the fix is < 5 mins time. Basically just don't conditionally register any packets. The side param to the register method takes care of all that.

**Comment by mysticdrew** [comment] 2018-08-08 01:56
Read what I said, when 1.13 comes out it will be fixed. Any more fuss and I will not merge any bug fixes down to 1.12.2. Don't you dare tell me how long something will take and how much free time I have. Enjoy your FREE mods.

**Comment by thiakil** [comment] 2018-08-08 15:45
> Don't you dare tell me how long something will take

It is a guesstimate of this fix *in isolation*, and as a fellow modder I can make such a guess.

> and how much free time I have

Nobody did. If you don't have *any* time, or don't wish to fix just one bug, *say so*, instead of getting cranky.

**Comment by mysticdrew** [comment] 2018-08-08 16:47
I already said when it will be fixed. I am not going to do one small fix and release it. I have a bunch of fixes I need to do, I will make time to do all in one go once 1.13 recommended forge is released. That is final, it will not change. No matter how much you bitch and moan.

**Comment by Celdecea** [comment] 2019-01-14 01:45
@Weissmoon said:

> I fixed it with [this](https://minecraft.curseforge.com/projects/journeymapfixer/files/2586654).

Thank you. Works perfectly.

**Closed** 2019-01-28 16:31 UTC
Labels: a:bug, in:client, jm:5.5.2, mc:1.12.2

**Comment by hron84** [comment] 2019-02-18 04:31
Can we get any ETA for 5.5.4 release?
