### ISSUE TITLE
[1.12.2] [Feature] Category Waypoints

### ISSUE THREAD

**Issue by Ronnie0982** [TeamJM/journeymap#70] opened 2018-09-27 18:31 UTC
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`: 1.12.2-5.5.2`

#### Forge Version:
1.12.2-14.23.4.2760`

#### Describe the problem in repeatable steps:

I don't have any problem, but it's just a feature that could be used in many cool ways to say that these waypoints is made to this group, and enable them if they need

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No logs just a asked feature

**Comment by BrainStone** [comment] 2018-09-27 18:52
Duplicate of #28

**Closed by BrainStone** 2018-09-27 18:52 UTC
