### ISSUE TITLE
[Crash]: when trying to make a waypoint

### ISSUE THREAD

**Issue by EgertSUS** [TeamJM/journeymap#754] opened 2024-07-06 08:24 UTC
### What happened?

A crash happened!

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot invoke "journeymap.common.nbt.waypoint.WaypointDAO.deleteWaypoint(journeymap.common.waypoint.WaypointImpl)" because "this.dao" is null

**Comment by mysticdrew** [comment] 2024-07-06 09:17
Please provide full logs

**Comment by mysticdrew** [comment] 2024-07-06 17:03
I need your latest crash log `minecraft/crash-reports/DATE-client.txt`, your `minecraft/journeymap/journeymap.log` and `minecraft/logs/latest.log`

Please upload these files so I can see what is going on and fix it. 

This issue will be marked as waiting for response, and will be closed in 24 hours if there is no response.

**Comment by mysticdrew** [comment] 2024-07-07 15:54
Closing as Stale, no logs provided.

**Comment by nojvspine** [comment] 2024-07-26 22:49
I'm having the same issue, here's the files
[crash-2024-07-27_02.45.04-client.txt](https://github.com/user-attachments/files/16397266/crash-2024-07-27_02.45.04-client.txt)
[journeymap.log](https://github.com/user-attachments/files/16397268/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16397269/latest.log)

**Comment by mysticdrew** [comment] 2024-07-27 02:27
> I'm having the same issue, here's the files [crash-2024-07-27_02.45.04-client.txt](https://github.com/user-attachments/files/16397266/crash-2024-07-27_02.45.04-client.txt) [journeymap.log](https://github.com/user-attachments/files/16397268/journeymap.log) [latest.log](https://github.com/user-attachments/files/16397269/latest.log)

Thanks for providing logs

**Comment by mysticdrew** [comment] 2024-08-09 21:51
I did some more optimizations to waypoint saving. 
Please see if the issue is resolved with 1.21-6.0.0-beta.19

**Comment by AaronSzaboo** [comment] 2024-08-10 11:43
I've had a crash too when trying to make a waypoint, in the All the Mods 10 modpack. 
[crash-2024-08-10_13.36.11-client.txt](https://github.com/user-attachments/files/16569402/crash-2024-08-10_13.36.11-client.txt)
[journeymap.log](https://github.com/user-attachments/files/16569403/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16569404/latest.log)
The main error seems to be the "java.lang.NullPointerException: Cannot invoke "journeymap.client.ui.component.dropdown.DropDownItem.getId()" because the return value of "journeymap.client.ui.component.dropdown.DropDownButton.getSelected()" is null" part.

**Comment by mysticdrew** [comment] 2024-08-10 15:33
> I've had a crash too when trying to make a waypoint, in the All the Mods 10 modpack. [crash-2024-08-10_13.36.11-client.txt](https://github.com/user-attachments/files/16569402/crash-2024-08-10_13.36.11-client.txt) [journeymap.log](https://github.com/user-attachments/files/16569403/journeymap.log) [latest.log](https://github.com/user-attachments/files/16569404/latest.log) The main error seems to be the "java.lang.NullPointerException: Cannot invoke "journeymap.client.ui.component.dropdown.DropDownItem.getId()" because the return value of "journeymap.client.ui.component.dropdown.DropDownButton.getSelected()" is null" part.

yours is unrelated, please make a new issue

**Comment by AaronSzaboo** [comment] 2024-08-10 16:33
@mysticdrew I'm glad to know it is known issue that has already been fixed. I've made the new issue, as you asked: https://github.com/TeamJM/journeymap/issues/771.

**Comment by nojvspine** [comment] 2024-08-11 00:18
> I did some more optimizations to waypoint saving. Please see if the issue is resolved with 1.21-6.0.0-beta.19

Did a check on updated version, the game no longer crashes, thanks!

**Comment by mysticdrew** [comment] 2024-08-24 23:13
going to close as completed. 
Please let me know if it happens again.

**Closed by mysticdrew** 2024-08-24 23:13 UTC
Labels: waiting-for:response, a:crash
