### ISSUE TITLE
[Bug]: Group Waypoint Toggle

### ISSUE THREAD

**Issue by 100xdonaldx001** [TeamJM/journeymap#808] opened 2024-10-17 19:49 UTC
### What happened?

The Group Waypoint toggle doesnt work on all Group waypoints.

It either does none or only a couple like 1-2

Example: Farming Group is off:
![image](https://github.com/user-attachments/assets/bccea632-f04f-4857-b7dd-0469519f35f0)

Example Farming group is on:
![image](https://github.com/user-attachments/assets/80a5d642-5e02-4778-bed2-298ee5006bd7)

A Temporary resolve is to edit every Waypint manually but as visible on some of my groups there It can take a while for it to toggle on and off manually.

### Mod Loader

Forge

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment] 2024-10-17 19:57
Enabling/Disabling groups does not update the waypoints. 

So if you have 2 waypoints enabled, 10 disabled. 
You disable the group, now it shows all waypoints are disabled because the group is enabled. But, if you turn the group back on, it will not enable the waypoints that were previously disabled. It will only enable the waypoints that were already enabled. 
This is the intended behavior.

**Comment by mysticdrew** [comment] 2024-10-17 19:59
to enable/disable all the waypoints themselves in the group, click the button on the top header line of the waypoints. 
![image](https://github.com/user-attachments/assets/e3842d64-2688-4305-9990-a600eeda023a)

**Comment by 100xdonaldx001** [comment] 2024-10-17 20:59
> to enable/disable all the waypoints themselves in the group, click the button on the top header line of the waypoints. ![image](https://private-user-images.githubusercontent.com/5459941/377616041-e3842d64-2688-4305-9990-a600eeda023a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxOTg2OTQsIm5iZiI6MTcyOTE5ODM5NCwicGF0aCI6Ii81NDU5OTQxLzM3NzYxNjA0MS1lMzg0MmQ2NC0yNjg4LTQzMDUtOTk5MC1hNjAwZWVkYTAyM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMjA1MzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE5NTJhMTlkNWY1NjllNjQyMzUwNjVkNDFiNDZiZjBkZjdlYmZkNGIyN2VhM2UyZTM5ZTIwZDlhMDg3ZjcwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ec1fTnlVtVZMNxyxGapPsFTGfsjakAwmwaT5qVWXg8k)

I would understand if that would be the case but it isnt.
It does the same as the left toggle for the group

And additionally when that bug occours i cant even toggle the waypount itself with the toggle button next to it.
I would need to edit the waypoint in order to enable it again.

See here:
https://github.com/user-attachments/assets/a36818a4-13c5-448f-b721-e41fa2b5cf5f

**Comment by mysticdrew** [comment] 2024-10-17 22:22
What beta version are you on? I am unable to replicate this. 
Can you please send me your waypoints.dat file for this world please?

**Comment by 100xdonaldx001** [comment] 2024-10-17 22:29
Its beta version 27 (latest)
![image](https://github.com/user-attachments/assets/6ea77389-1421-4843-96b0-d872fcb73873)

And hers the Waypoint file in zip cause Github doesnt allow .dat files:
[Uploading WaypointData.zip…]()

**Comment by mysticdrew** [comment] 2024-10-17 22:46
Thanks, looking into it.

**Comment by mysticdrew** [comment] 2024-10-17 22:51
Does restarting fix it? 
With your waypoint file, I see no issues. Everything is working as intended. 
I will load up wynn craft and see I suppose. 

Can you give me a step by step on reproducing it? Maybe I am doing something wrong here.

**Comment by 100xdonaldx001** [comment] 2024-10-17 23:06
I dont really have a step by step instruction for the issue. it randomly happens.

Like i join the hub and everything works as intended.
I can do everything toggle waypoints, toggle group, toggle all
I then join the server and sometimes everything still works
sometimes tho i cant toggle waypoints, toggle groups works for some but not all groups
Toggle all waypoints work in some but not all groups.

Tho when i am on an server and toggle all waypoints and then reconnect to the hub all waypoints then are activated.
so when i join a server again they show and ican do everythign with them again like disable enable toggle all.

So i cant really tell where exactly the issue is even tho i would like to.

**Comment by mysticdrew** [comment] 2024-10-17 23:09
I was able to replicate it on the server. I wonder if changing dims in SP does it too.

**Comment by mysticdrew** [comment] 2024-10-18 00:23
Okay, I think I found the problem. If you pop into our discord, i can give you a test build to verify.

**Comment by mysticdrew** [comment] 2024-10-31 15:30
This is fixed for beta.29 when I release it

**Comment by mysticdrew** [comment] 2024-11-01 21:46
fixed in beta.29, it will be available in CF/MR shortly

**Closed by mysticdrew** 2024-11-01 21:46 UTC
Labels: a:bug, status:fixed
