### ISSUE TITLE
[1.21]: Crash when opening fullscreen map

### ISSUE THREAD

**Issue by BBoldt** [TeamJM/journeymap#732] opened 2024-06-22 18:19 UTC
### What happened?

When pressing the keybind to open the fullscreen map, game closes entirely.

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

https://gist.github.com/BBoldt/39b2785a174beafadb33f3d6d64d7cc9

**Comment by mysticdrew** [comment] 2024-06-22 18:22
looks to be caused by  dev.architectury.impl.fabric.ScreenInputDelegate$DelegateScreen.method_25400(ScreenInputDelegate.java:42)

**Comment by mysticdrew** [comment] 2024-06-22 18:35
I added architectury and did not have a fail. So there is likely another mod that uses the api causing the conflict. 
My suggestion is to disable architectury, see what mods yell at you because it is not installed. 
Then start disabling those one by one to see which one is causing it so either I can try fixing it on my end or let them know what needs to be fixed.

**Comment by BBoldt** [comment] 2024-06-22 19:15
Okay I'll try to figure out which one it is.

**Comment by BBoldt** [comment] 2024-06-22 20:25
So, it's really strange. Seems to be something to do with this mod, Visual Overhaul. 
https://www.curseforge.com/minecraft/mc-mods/visual-overhaul

The issue stops when I have that mod disabled, but I can't reproduce the issue with *only* journeymap and visual overhaul. So it's clearly _visual overhaul + journeymap + ??? = crash_. I just can't figure out what is the final mod in the equation. At least it's fixed with visual overhaul disabled so that's something.

**Comment by mysticdrew** [comment] 2024-06-24 23:18
That means adding VO and start adding other mods? 
What about achitectuary + vo + jm?

**Comment by mysticdrew** [comment] 2024-06-24 23:19
It gets really difficult when there are several mods in combo breaking. 
I once had a combination of 4 mods causing JM to break. Took me a long time to figure it out.

**Comment by BBoldt** [comment] 2024-06-24 23:26
I spent like an hour trying different mod combinations and kinda gave up.
I looked through their issue tracker and noticed some similar issues with other mods involving GUIs being activated, but it must be certain combinations that trigger it. 

https://github.com/TeamMidnightDust/VisualOverhaul/issues/

I also noticed some bugs there relating to other mods in my pack, so I ended up removing it.

**Comment by mysticdrew** [comment] 2024-06-25 01:59
fair enough, thanks for putting in the effort. I'll leave this open for a bit so I can look into it when I get some time.

**Comment by tajemniktv** [comment] 2024-07-03 11:59
Thanks for opening this issue, I was also faced with this crash but removing Visual Overhaul has helped

**Comment by mysticdrew** [comment] 2024-07-05 14:32
> Thanks for opening this issue, I was also faced with this crash but removing Visual Overhaul has helped

@tajemniktv do you happen to have a mod list? I have been trying to investigate this issue and have not been able to replicate it. Though VO has had some updates related to crash fixes, maybe they fixed it on their end?

**Comment by tajemniktv** [comment] 2024-07-05 15:24
These are some of the recent logs I posted because of an issue with some other mod (full log from Prism, so java, mod list, specs etc.): https://mclo.gs/8XymbVM

Some things have changed, I added, removed and updated some mods since then, so I can try installing VO once again to check whether the issue in this modpack combo still persists when I get back to PC, but for now that's all I can provide... I'll get back to you in an hour or so

**Comment by mysticdrew** [comment] 2024-07-05 17:59
> These are some of the recent logs I posted because of an issue with some other mod (full log from Prism, so java, mod list, specs etc.): https://mclo.gs/8XymbVM

an issue with journeymap and another mod?

**Comment by tajemniktv** [comment] 2024-07-05 18:03
Nah nah,

**Comment by tajemniktv** [comment] 2024-07-05 18:04
> an issue with journeymap and another mod?
Nah, it had to do with some connected textures and stuff. 

Here's the latest log with Visual Overhaul installed as well: https://mclo.gs/Dr3velI

**Comment by mysticdrew** [comment] 2024-07-05 18:21
No, it is a text field in the fullscreen map. Something is injecting in to Minecraft's Screen class and probably breaking the init method. 

In prism, can you add this `-Dmixin.debug.export=true` to the java arguments section. 
Run the game, make the crash happen. 
![image](https://github.com/TeamJM/journeymap/assets/5459941/e9f78241-437a-4d6a-9cc7-0ea806d87b6f)

Then in the minecraft folder folder called `.mixin.out` in there can you attach the file. 
`net.minecraft.class_437.class` please

**Comment by tajemniktv** [comment] 2024-07-05 18:30
Logs: https://mclo.gs/IVlibGV
Had to put it into the zip: [class_437.zip](https://github.com/user-attachments/files/16112820/class_437.zip)
I hope I went into the right folder lol
![image](https://github.com/TeamJM/journeymap/assets/12156943/7dbca5ef-0dc6-401c-aab7-c45f266ce3aa)

**Comment by mysticdrew** [comment] 2024-07-05 18:59
Thanks!!
Okay.. so this gave me a bit more to go on, but still a mystery. 
Can you disable architectury API and give me a list list of mods that blow up without it? A mod that depends on architectury is causing the issue, so this will narrow it down significantly.

**Comment by tajemniktv** [comment] 2024-07-05 19:50
Huh, that's interesting
![image](https://github.com/TeamJM/journeymap/assets/12156943/87aa7ecb-b7b5-4131-8292-86d582a5e5fc)

**Comment by mysticdrew** [comment] 2024-07-05 19:53
Hmm, thanks. I figured there would be more? Maybe fabric only reports the first one loaded

**Comment by tajemniktv** [comment] 2024-07-05 19:55
Yeah that's why I'm also surprised - I turned off this JamLIB mod and waiting for a game to start, but it's not only taking some time but I can also see a shit ton of errors in console related to... REI?
![image](https://github.com/TeamJM/journeymap/assets/12156943/27952dab-4610-46dd-8189-4bfd1c9fa9ef)

**Comment by mysticdrew** [comment] 2024-07-05 20:09
Okay so not related architectury then since you removed it and jamlib. 
This is all so confusing. 
Is this a public pack?

**Comment by tajemniktv** [comment] 2024-07-05 20:17
Actually when I remove both architectury it just won't load my game and simply freeze it. Here are logs from trying to run it without Architectury: https://mclo.gs/PPmK6EN
I can try without REI, maybe? 
![image](https://github.com/TeamJM/journeymap/assets/12156943/59174124-573c-4afb-8d08-e16ba7cd9d4e)


The pack I'm using is made by me, basically throwing everything I find interesting, I can send you a zip or mrpack if you might need it

**Comment by mysticdrew** [comment] 2024-07-05 20:18
It is fancy menu + vo

**Comment by mysticdrew** [comment] 2024-07-05 20:18
It is fancy menu + vo

**Comment by mysticdrew** [comment] 2024-07-05 20:18
OOPS didin't mean to close it

**Comment by tajemniktv** [comment] 2024-07-05 20:18
shit bruh, no way

**Comment by mysticdrew** [comment] 2024-07-05 20:19
yea, the class file you sent me earlier, i was going through that and adding mods one at a time that inject into the screen class.

**Comment by tajemniktv** [comment] 2024-07-05 20:22
Ah damn, glad I could be somehow helpful. Pity, I find fancymenu pretty useful, especially in modpacks that add a lot of buttons. I wonder is there a way to block Fancymenu to stop from injecting into that one screen class? i believe i saw that option somewhere in their settings, not sure whether that completely blocks it tho. is that fixable from your side, or should we create an issue for fancymenu and/or VO?

**Comment by mysticdrew** [comment] 2024-07-05 20:28
I can probably fix it, I think I see what the issue is. Though, not sure why FM + VO causes the issue, I would think just FM would cause it.

**Comment by tajemniktv** [comment] 2024-07-05 20:31
Yeah, that's interesting, what role does VO play here? Maybe the icons on the buttons somehow break things?
![image](https://github.com/TeamJM/journeymap/assets/12156943/3b61593e-5041-4ab9-ac38-92624c1e9d79)

**Comment by mysticdrew** [comment] 2024-07-06 11:57
Okay, I have this fixed for the next beta release. 
This was related to some buttons on the fullscreen map. 
Seems the combination of FM and VO called methods in the constructor before the button was full built, causing an NPE.

I will close once it is released

**Comment by tajemniktv** [comment] 2024-07-06 11:58
Incredible, thanks for your work drew!

**Comment by mysticdrew** [comment] 2024-07-08 01:11
1.21-6.0.0-beta.15 with the fix is publishing, should be available in the next 30 minutes

**Closed by mysticdrew** 2024-07-08 01:11 UTC
Labels: a:crash

**Comment by tajemniktv** [comment] 2024-07-08 08:11
Can confirm that it now doesn't crash and works just fine with VO and other 200+ mods:))
