### ISSUE TITLE
[Suggestion]: Quark Vanilla Overridden mob icons do not display.

### ISSUE THREAD

**Issue by FelipeCardona95** [TeamJM/journeymap#352] opened 2021-12-03 03:04 UTC
#### JourneyMap Version:

 journeymap-1.16.5-5.7.3

#### Forge Version:

Forge 36.2.8
#### Describe the problem in repeatable steps:

1.Have quark installed
2.Enable Mob Icons
3.Not all mob icons are showing correctly

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[20:40:42] [JM-task-4/ERROR] [VanillaBlockSpriteProxy] Error during [RenderType[CompositeState[[texture[Optional[minecraft:textures/atlas/blocks.png](blur=false, mipmap=true)], no_transparency, diffuse_lighting[false], shade_model[smooth], alpha[0.0], depth_test[<=], cull[true], lightmap[true], overlay[false], fog, no_layering, main_target, default_texturing, write_mask_state[writeColor=true, writeDepth=true], line_width[1.0]], outlineProperty=affects_outline]]] class com.simibubi.create.foundation.block.render.ColoredVertexModel.getQuads(Block{create:natural_scoria}, up, 0): java.lang.NullPointerException

![image](https://user-images.githubusercontent.com/11274437/144538168-8543ccdb-baf6-4656-bfb9-1a8b624fab85.png)

**Comment by mysticdrew** [comment] 2021-12-03 03:14
That error has nothing to do with this, but that's fine. 
Quark overrides vanilla mobs so we do not have icons for them. We need to create a workaround so if it is a quark mob, we use vanilla icon.

**Comment by mysticdrew** [comment] 2022-01-21 20:12
So, solve this, someone would need to create icons for the quark entities and use them in a resource pack or give the icons to me so I can supply them in journeymap. 
I am going to close this since this is not a bug or a code issue. This is an issue that happens with all mods that add mobs.

**Comment by mysticdrew** [comment] 2022-03-28 01:24
[quarkicons.zip](https://github.com/TeamJM/journeymap/files/8358996/quarkicons.zip)
these icons need to be added, reopening so I do not forget!

**Comment by mysticdrew** [comment] 2022-04-14 02:49
These will be added in 1.16.5 1.18.1 and 1.18.2(forge and fabric). 5.8.1beta4 when published

**Closed** 2022-04-15 16:12 UTC
Labels: a:enhancement, in:client, status:completed, a:mod-interaction, mc:1.16.5, mc:1.17.1, jm:5.8.0, mc:1.18.1
