### ISSUE TITLE
[1.16.5] [Feature] Further fullscreen map zoom out

### ISSUE THREAD

**Issue by Brycey92** [TeamJM/journeymap#344] opened 2021-11-24 17:45 UTC
#### JourneyMap Version:

`Example: 1.16.5-5.7.3`

#### Forge Version:

`Example: 1.16.5-36.2.16`

#### Describe the problem in repeatable steps:

On large worlds, it's very difficult to find things you're looking for, and impossible to see the whole world at once because the fullscreen map does not zoom out far enough. Other map mods allow zooming out far more than JourneyMap does.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

N/A

**Comment by gdude2002** [comment] 2021-11-24 17:48
Duplicate of #126, #129, #257, #284 and #328

**Closed by gdude2002** 2021-11-24 17:48 UTC
