### ISSUE TITLE
[1.18.2] Waypoint OpenGL Error 1282

### ISSUE THREAD

**Issue by 1-1037** [TeamJM/journeymap#412] opened 2022-03-31 05:36 UTC
**JourneyMap Version:**
journeymap-1.18.2-5.8.1beta2.jar

**Forge Version:**
forge-1.18.2-40.0.23

**Describe the problem in repeatable steps:**
Whenever I make, edit, or interact with any waypoints,  I get tons of OpenGL Error 1282 in the chat, and usually after, it makes my textures glitch. This only happens when playing with Optifine (1.18.2 HD U H6 and 1.18.2 HD U H7 pre3). I did try multiple worlds and it kept happening, even with just Optifine and JourneyMap installed. **The error itself doesn't happen when Optifine isn't installed.**
The error only fixes itself once restarting Minecraft, closing and reopening a world doesn't fix it.

**Relevant errors from .minecraft/journeymap/[journeymap.log]**
The error from latest.log, repeated a ton of times;
>[00:20:41] [Thread-62/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.)
java.lang.Exception: Stack trace
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:180) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2346!/:build 10] 

[latest.log](https://github.com/TeamJM/journeymap/files/8386265/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/8386253/journeymap.log)

**Comment by benwong01f611** [comment] 2022-03-31 08:07
Optifine is causing tons of issues, but this will be fixed (probably, I still get OpenGL Error 1282 but not related to JM) in next release as Mysticdrew had found the potential issue.

**Comment by mysticdrew** [comment] 2022-03-31 22:22
https://github.com/sp614x/optifine/issues/6731

**Comment by mysticdrew** [comment] 2022-03-31 22:23
This is a bug with optifine

**Comment by mysticdrew** [comment] 2022-04-02 14:42
Pinning this issue. 
I have made some improvements but I am unable to resolve this completely. Most likely due to a bug in optifine.

**Comment by EthanHunt404** [comment] 2022-05-09 03:35
the ug seems related with the beacons they are stange in 1.18.2

**Comment by wolvyreen** [comment] 2022-05-20 06:08
I can confirm I am seeing this exact same issue.  The moment I interact with any waypoints, I get glitching textures and opengl errors. 

I am also running JM and optifine 1.18.2 H7

**Comment by yangrq1018** [comment] 2022-07-20 02:42
I am having this too. OpenGL 1282 errors randomly pop out after I teleport through waypoints for a few times.

**Comment by wolvyreen** [comment] 2022-07-20 06:30
> I am having this too. OpenGL 1282 errors randomly pop out after I teleport through waypoints for a few times.

Drop forge and optifine for fabric and an alternative like iris. Problem solved.

**Comment by mysticdrew** [comment] 2022-07-25 17:46
This will be fixed in 5.9.0, I think I have the new texture engine issues resolved. 
Doing another round of "other" bug fixes and then a beta of 5.9.0 will be released. No time frame yet as my life is very busy

**Closed** 2022-07-28 15:23 UTC
Labels: a:bug, status:invalid, status:fixed, waiting-for:external, status:completed, a:mod-interaction, mc:1.18.2, loader:forge
