### ISSUE TITLE
[MC 1.18.1] Journey Map keybinds not saving when using Default Options, reverts back to default values.

### ISSUE THREAD

**Issue by Gbergz** [TeamJM/journeymap#378] opened 2022-01-16 23:17 UTC
#### JourneyMap Version:
`1.18.1-5.8.0beta9`

#### Forge Version:

`39.0.19`

#### Describe the problem in repeatable steps:

1. Install Journey Map & Default Options in a new profile within the CurseForge app.
2. Launch game and change any Journey Map keybind to any other keys than default.
3. Join a world and run `/defaultoptions saveAll`.
4. Quit Game.
5. Export Profile (include config folder).
6. Import profile created profile.
7. Start the Game.
8. Go into controls and check changed keybinds.
9. Keybinds have been reverted to default values.
10. Profit.

Found an issue back in 2017 showing the exact same issue, was fixed but it seems to have returned?.
`https://github.com/TeamJM/journeymap/issues/2`

**Reported the issue here aswell:**
`https://github.com/ModdingForBlockheads/DefaultOptions/issues/56`

**-** Gbergz

**Comment by mysticdrew** [comment] 2022-01-16 23:20
#2 was for a version that was scrapped due to it having a lot of bugs and techbrew had to depart from JM dev and I was on a hiatus at the time. I will investigate. 

I think I know why it is happening by reading his comments.

**Comment by mysticdrew** [comment] 2022-01-17 02:20
if you are able to come into our discord, I can give you a test version so you can verify on your end that it is fixed.

**Comment by Gbergz** [comment] 2022-01-17 10:13
Already a member of your discord. 👍

**Comment by mysticdrew** [comment] 2022-01-17 22:39
Ok so, I have changed up JM keybindings registration so it should work once Default Options is updated as it is not working at all for 1.18.1. I cannot get Default Options to work with plain vanilla keybindings and no other mods installed.
My fix for this will be in beta10 when published to curseforge. 

Once default options keybindings are working again, I will revisit and make any needed changes if it does not work with beta 10 and later.

**Comment by mysticdrew** [comment] 2022-01-21 20:09
It has been confirmed by @Gbergz that when default options is working that beta 10 fixes the defaultoptions issue.

**Closed by mysticdrew** 2022-01-21 20:09 UTC
Labels: status:external-issue, waiting-for:external, in:client, a:mod-interaction, mc:1.16.5, mc:1.17.1, jm:5.8.0, mc:1.18.1
