### ISSUE TITLE
[Bug]: Auto-Map is leaving large blank areas of loaded chunks.

### ISSUE THREAD

**Issue by otherguy223** [TeamJM/journeymap#807] opened 2024-10-14 17:47 UTC
### What happened?

During the auto-map process, every finished region only renders the left side of the tile and the rest stays blank. 

File: journeymap-neoforge-1.21-6.0.0-beta.27
![2024-10-14_13 43 08](https://github.com/user-attachments/assets/8b5e7587-6137-4862-b8d7-043642382e7a)

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/17367576/journeymap.log)

**Comment by mysticdrew** [comment] 2024-10-14 17:56
please add your latest.log also

**Comment by otherguy223** [comment] 2024-10-14 18:07
[latest.log](https://github.com/user-attachments/files/17367829/latest.log)

**Comment by mysticdrew** [comment] 2024-10-14 18:17
I've been this with the cme mod. I don't see it in your list. Though, it is hard to read on mobile. If you have any chunk loading optimization mods disable them and see if that fixes it and let me know if it does which mods. So, I can look at fixing it.

**Comment by otherguy223** [comment] 2024-10-14 20:33
The pack I am using is All The Mods 10 on NeoForge 1.12.1 v21.1.68 it is the default mod list and I have added either Chunky v1.4.16 or Chunk Pre-Generator v1.21-4.4.5. Never at the same time. I only tried two because I was getting the same error for pre-loading the world.

The pack includes Sodium

Other than that, I don't have any additional mods that would alter chunk generation.

**Comment by otherguy223** [comment] 2024-10-14 20:35
I have also done the basic troubleshooting. Fresh installs, restarting the client, different worlds... The works,.

**Comment by brendenhoffman** [comment] 2024-10-17 00:27
Hi I have the same problem in my pack and I do not have c2me (while I was testing this), I also disabled noisium fwiw. I looked through OP's mod pack and there are not a lot of similarities besides sodium and a few tech mods. I confirmed auto map works with vanilla.

[latest.log](https://paste.gg/p/anonymous/246d2598422b4f1d94432ea0d9a14459)

[journeymap.log](https://paste.gg/p/anonymous/385fff30d4014ae798b9ae6b6d6973f7)

Anything else you think could be the culprit?

**Comment by mysticdrew** [comment] 2024-10-17 00:31
That problem is a change we made that was slowing down automap.  It is taking 40+ seconds per region. Should take 5s. So the chunks are getting removed from memory before the region finishes. I think I have it fixed. I need to do more testing, will be in the next beta.

**Comment by mysticdrew** [comment] 2024-10-17 00:34
> Hi I have the same problem in my pack and I do not have c2me (while I was testing this), I also disabled noisium fwiw. I looked through OP's mod pack and there are not a lot of similarities besides sodium and a few tech mods. I confirmed auto map works with vanilla.
> 
> [latest.log](https://paste.gg/p/anonymous/246d2598422b4f1d94432ea0d9a14459)
> 
> [journeymap.log](https://paste.gg/p/anonymous/385fff30d4014ae798b9ae6b6d6973f7)
> 
> Anything else you think could be the culprit?

I think you got lucky it worked in vanilla.

**Comment by brendenhoffman** [comment] 2024-10-17 00:44
I was about to make another issue because with a 2048 build height my map looks like this:

![Screenshot_20241016_163218](https://github.com/user-attachments/assets/b0270fdf-bf2a-455d-9638-91361737a0df)

Could that be caused by the same thing you think? I'm going to do another vanilla test with an increased build height. But if the chunks take up more space in memory I could definitely see why it would start to look like this.

Auto map speed used to be configurable right? I would love the option to use my whole cpu, I paid for all these cores afterall.

**Comment by mysticdrew** [comment] 2024-10-17 01:12
your first images with the spotty thing may be a different issue. 
If it is still happening after beta.28 is released(hopefully tomorrow) create a new issue about it please.

**Comment by brendenhoffman** [comment] 2024-10-17 01:19
Yeah that was the plan. Fingers crossed you fixed the issue. 

I wish I got a picture, but in my first comment there were still some spotty chunks, but they showed up before I hit auto map strangely enough. But there is a few below my position in the last picture too and that was a completely clean instance.

**Comment by otherguy223** [comment] 2024-10-17 01:27
Really appreciate the efforts. Regular exploring filled in the chunks so
far, but it’s defeating the purpose of pregenerating my worlds.

**Comment by mysticdrew** [comment] 2024-10-18 00:27
this is fixed in beta.28 which is released now on CF and MR

**Closed by mysticdrew** 2024-10-18 00:27 UTC
Labels: a:bug, waiting-for:response

**Comment by otherguy223** [comment] 2024-10-21 01:57
Yup! All resolved in beta.28! Thanks!

**Comment by brendenhoffman** [comment] 2025-11-05 18:49
That doesn't exactly look like the same issue. Your map has a pattern of something that would be generated by a player. Auto map doesn't just fill in unloaded chunks.

You might want to create a new issue if you have problems like auto map doing nothing or partially generating. A good way to test is to generate your world with something like chunky, then hit auto map. Or turn off mapping, run around, then auto map.
