### ISSUE TITLE
[1.12.2]Rare bug: mini maps cannot be drawn

### ISSUE THREAD

**Issue by Flithor** [TeamJM/journeymap#62] opened 2018-07-12 18:51 UTC
#### JourneyMap Version:

1.12.2-5.5.2`

#### Forge Version:

1.12.2-14.23.3.2678

#### What's happened:

This bug with mini map, occasionally can't be drawn map texture in mini map,
usually appearing in zooming mini map or entry caves.

Usually expressed as:
Cannot display any map texture at A scale in mini map, but can be displayed when zoomed to other scale
Zooming still can't display the map texture in a mini map.
Not continue to draw texture after move to the texture un-drawn area
Texture is not displayed in the mini map, but the texture is normal display in the full screen map.
Trying to automatical drawing the map does not make the mini map display the drawn texture.
...

The situation may complex.
Recommended to set this issue as a long-term issue and wait for more feedback.

Edit:
I found that can using the "display mode change" hotkey can refresh the minimap texture.

**Comment by HydrogenC** [comment] 2018-11-18 02:17
Is this the same situation? The minimap isn't rendered. 
(forge1.12.2-14.23.5.2768 & jm-5.5.2)

![2018-11-18_10 16 15](https://user-images.githubusercontent.com/33123710/48667858-0bd5b780-eb1b-11e8-9105-f676dfc23f7a.png)

**Comment by mysticdrew** [comment] 2019-04-04 18:51
Is this still an issue with 5.5.4?

**Comment by Flithor** [comment] 2019-04-04 23:53
yes

**Comment by mysticdrew** [comment] 2019-04-05 01:48
Ok, I will close this for now then. But I will still investigate it.

**Comment by mysticdrew** [comment] 2019-04-15 22:08
I know what the issue is now, but I do not know what is causing it. 

For my future reference. 
Maptype is being set to "MapType.none"

**Comment by mysticdrew** [comment] 2019-12-21 21:06
I found the issue and it is fixed for 1.14.4, not sure if I will push another release out for 1.12.2.
It was getting locked into Underground or Cave mode when logging in.

**Closed by mysticdrew** 2019-12-21 21:06 UTC
Labels: a:bug, in:client, jm:5.5.2, mc:1.12.2, waiting-for:response
