### ISSUE TITLE
Crash 1.19.2 Fabric

### ISSUE THREAD

**Issue by papillo12** [TeamJM/journeymap#537] opened 2022-12-15 09:53 UTC
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Upload your log files or use gist, pastebin, or some similar site. Pasting log contents directly into the issue will get the issue closed immediately.
5. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
6. #### Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`journeymap-1.19.2-5.9.0beta5-fabric.jar`

#### Fabric Version: 0.14.11

`1.19.2-0.14.11`

#### Describe the problem in repeatable steps:

I'm not really sure, just crashing

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[crash-2022-12-14_18.25.02-client.txt](https://github.com/TeamJM/journeymap/files/10235821/crash-2022-12-14_18.25.02-client.txt)

**Comment by papillo12** [comment] 2022-12-16 01:13
[journeymap.log](https://github.com/TeamJM/journeymap/files/10241876/journeymap.log)

**Comment by papillo12** [comment] 2022-12-16 01:13
[latest (3).log](https://github.com/TeamJM/journeymap/files/10241878/latest.3.log)

**Comment by mysticdrew** [comment] 2022-12-16 01:49
Neither of those logs have the crash in it. Which is fine I guess. 
Any chance you can hop in our discord, I can give you a build to see if it resolves the issue.

**Comment by papillo12** [comment] 2022-12-16 02:44
sorry, it is difficult for me to get the files because the crashes were reported to me by a player of the server and they don't know how to look for the files I need

**Comment by papillo12** [comment] 2022-12-16 02:47
and yes, please send me the build

**Comment by mysticdrew** [comment] 2022-12-16 13:03
You will need to come into discord for it.

**Comment by mysticdrew** [comment] 2022-12-18 00:02
Not sure what happened, with them in discord. But anyways, the next version will have a potential fix. 
I will close this ticket when it is released

**Comment by mysticdrew** [comment] 2022-12-22 16:32
So with 5.9.0 release, I put in some protections to prevent the crashes. It does not fix the problem but it should in theory prevent the crash until we can find the cause. 
Release will be on curseforge and modrinth shortly.

**Closed** 2022-12-22 16:32 UTC
Labels: a:bug, waiting-for:response, status:completed, a:crash

**Comment by papillo12** [comment] 2022-12-22 19:05
okay, I will update to fix that crash this week and thank you
