### ISSUE TITLE
Freeze whenever I try to update the main map - 1.12.2

### ISSUE THREAD

**Issue by RodrigoTaipe93** [TeamJM/journeymap#210] opened 2020-04-24 18:59 UTC
### Forge Version: 1.12.1-14.23.5.2854`

###Describe the problem in repeatable steps:

1. Update to latest version

2. Whenever I try to update the map (the one you get pressing J), the screen freezes. This didn't happened with the previous versions of JM; even if I had a lot of mods.

###Relevant errors from `.minecraft/journeymap/journeymap.log`:

I updated the map at the last part of my session, so info is at the end. I'm not a programmer, so I wouldn't tell any particular part of the log as "strange"

[latest.log](https://github.com/TeamJM/journeymap/files/4530962/latest.log)

**Comment by gdude2002** [comment] 2020-04-24 19:02
Can you explain what you mean by "updated the map"?

**Comment by RodrigoTaipe93** [comment] 2020-04-24 19:17
Sure! When you press J, in your screen appears a big map of the world, right? So, when I explore, there are spots that are not shown; so I "update" the map. I don't remember the options name. I checked your website, I think the name is: "Auto-Map entire single-player worlds"
It fills the blank spots and you have an updated image of the entire region you explored.

So, before the latest version of Journey Map, the "Auto-Map entire single-player worlds" feature worked correctly. No lagging whatsoever; despite the many mods I installed. 
Now, with the latest version as the map is updating it freezes for around 3 or 5 minutes and then it works again.

That's basically it

**Comment by gdude2002** [comment] 2020-04-24 19:19
Okay. This is expected behaviour based on how intensive automapping actually is - it's designed to be run *once* to map an existing world, not to patch up the map when a chunk fails to render.

That said, chunks missing from the map is definitely a problem. Can you also upload your `journeymap.log`?

**Comment by RodrigoTaipe93** [comment] 2020-04-24 19:21
Ok! I will! Please, give me a little bit of time, since I usually delete my log sessions to save space. I will join my world again and during the day I will upload the journeymap log

**Comment by gdude2002** [comment] 2020-04-24 19:23
Logs really don't take up enough space to worry about for most people, but
okay.

Make sure you also upload a new `latest.log` with it, please.

**Comment by RodrigoTaipe93** [comment] 2020-04-24 23:18
This is the latest log:

- 
[latest.log](https://github.com/TeamJM/journeymap/files/4531946/latest.log)

and this is the latest log for Journey Map:

- https://paste.ee/p/c0Kbi

**Comment by gdude2002** [comment] 2020-04-25 08:44
There does appear to be some kind of incompatibility with a mod named `LLibrary`. 

Regardless, I wasn't looking for logs from when you automap - I wanted logs from when chunks aren't being rendered. Did you have that happen in this set of logs? Does that happen when you don't have Optifine?

**Comment by RodrigoTaipe93** [comment] 2020-04-26 03:49
I wouldn't know, to tell you the truth. I will explore other regions an upload a new log before updating the map.
I didn't try it. Didn't know there was an issue with Optifine; since I played with both mods for a long time and haven't seen any issues between the two. But, I will check it out!

**Comment by RodrigoTaipe93** [comment] 2020-04-26 06:12
Here are new latest log and journeymap log. Hope this helps somehow. I explored new terrain.

[2020-04-25-1.log.gz](https://github.com/TeamJM/journeymap/files/4534719/2020-04-25-1.log.gz)

- https://paste.ee/p/wyTXR

- https://paste.ee/p/tc9jk

**Comment by gdude2002** [comment] 2020-04-26 07:53
I'm not sure you understand what I'm asking for here.

The automap is intensive. It's going to slow down your client. This is normal.

I'm trying to figure out why you have chunks that aren't being mapped - your logs contain no errors, but I can see you're deleting the map and automapping again. That step isn't necessary.

---

Let's try something else. Enable the webmap (press `J`, press `O`, then enable it from the `Webmap` section), and open it in your browser by clicking on the link in chat.

Click the follow button at the top left. It looks like this: 
![image](https://user-images.githubusercontent.com/204153/80301276-18901d80-879b-11ea-8bc9-191e31a82b54.png)

Leave the webmap open, go back to the game, and play until you notice that chunks aren't being mapped.

As soon as you notice this, go back to the webmap, and check whether those chunks are visible there.

---

I have a hunch that this is a visual issue, and the chunks really are being mapped correctly - they're just not displaying. I'll need you to do the above, though.

**Comment by mysticdrew** [comment] 2021-02-21 19:32
1.12.2 is no longer supported. 
Closing this issue, if it is still a problem in 1.16, reopen and set the correct labels.

**Closed by mysticdrew** 2021-02-21 19:32 UTC
Labels: a:bug, in:client, jm:5.7.0, mc:1.12.2
