### ISSUE TITLE
[1.12.2] JourneyMap writes to config file continuously.

### ISSUE THREAD

**Issue by duckinator** [TeamJM/journeymap#82] opened 2018-12-13 02:43 UTC
JourneyMap writes to its config file continuously, to the point that it noticeably degrades the performance of the entire system.

Note: My debug steps likely only work on Linux, and use `strace`.

If you're unfamiliar with strace, here's info on some of the basics: https://jvns.ca/strace-zine-v3.pdf

#### JourneyMap Version:

1.12.2-5.5.2

#### Forge Version:

14.23.4.2707

#### Describe the problem in repeatable steps:

1. Start Minecraft.
2. Run: `watch -n1 stat journeymap.minimap.config`
    * This command does not actually access the file, so any changes it indicates are from elsewhere.
    * The `Change:` line, which indicates when the file was last written to, changes every time it updates.
    * This implies it's being overwritten at least once a second, as we confirm in detail in step 4.
3. Determine Minecraft's PID (e.g. using the `jps` command).
4. Run: `sudo strace -tt -e "trace=%file" -f -p $MINECRAFT_PID -o minecraft-strace.txt & sleep 60; sudo kill strace` 
    * Replace `$MINECRAFT_PID` with the PID determined in step 3 when running this.
    * This runs `strace` on Minecraft for 1 minute, tracking any system calls that access any files.
    * On my system, Minecraft overwrote `journeymap.minimap.config` 480 times in a minute(!).

Output of running that command on my system: https://boop.ws/minecraft-journeymap-strace.txt

It's a bit noisy, looking at `grep journeymap minecraft-journeymap-strace.txt`, it seems it's doing the following in an endless loop:

1. Running `stat()` on the file (indirectly, obviously, since that's the name of a Linux system call, not a Java function)
2. Opening the file with the following options:
    * write only (`O_WRONLY`),
    * create if it does not exist (`O_CREAT`),
    * truncate the file immediately (`O_TRUNC`), which means any writes it does will completely overwrite the contents.

I have absolutely no idea why it is doing this.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

There are no errors in this file.

**Comment by mysticdrew** [comment] 2019-04-02 02:05
So, I am unable to reproduce this issue with 5.5.4. It does a bit of I/O right when you load a world but then it does not do anything. 

What were you doing in the game while this was happening? 

Here is the snippit of logs I put in right before the File.write code. As you can see there is a bit of save spam when you load the world, but then it stops. 

`[21:00:38] [Server thread/INFO] [minecraft/MinecraftServer]: mysticdrew joined the game
[21:00:40] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[21:00:40] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'New World no mods'/overworld
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.core.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.fullmap.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.minimap.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.minimap2.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.minimap2.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.topo.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.webmap.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.waypoint.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.minimap.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.topo.config
[21:00:40] [main/INFO] [journeymap]: Loading journeymap.topo.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.topo.config
[21:00:40] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.minimap.config
[21:00:41] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.minimap.config
[21:00:41] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.minimap.config
[21:00:41] [main/INFO] [journeymap]: Loaded 2 waypoints from .\journeymap\data\sp\New World no mods\waypoints
[21:00:41] [main/INFO] [journeymap]: Mapping started in .\journeymap\data\sp\New World no mods\DIM0. Memory: 1188MB total, 608MB free 
[21:00:41] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.minimap.config
[21:00:41] [main/INFO] [minecraft/GuiNewChat]: [CHAT] JourneyMap: Press [J] or open browser to http://localhost:8080 
[21:00:41] [main/INFO] [journeymap]: JourneyMap: Press [J] or open browser to http://localhost:8080 
[21:00:41] [main/INFO] [STDOUT]: [journeymap.common.properties.PropertiesBase:save:375]: ------------------------------->journeymap.minimap.config
[21:00:54] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2044ms behind, skipping 40 tick(s)
[21:00:57] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[21:00:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'New World no mods'/overworld`

**Comment by mysticdrew** [comment] 2019-04-02 17:13
Unable to replicate. Closing for now until I get a response. @duckinator please verify this is still an issue in 5.5.4

**Closed by mysticdrew** 2019-04-02 17:13 UTC
Labels: a:bug, in:client, jm:5.5.2, mc:1.12.2, waiting-for:response
