### ISSUE TITLE
[1.10.2] Web map not showing map

### ISSUE THREAD

**Issue by Fevix** [TeamJM/journeymap#34] opened 2018-03-27 07:44 UTC
#### JourneyMap Version:

1.10.2-5.5.2

#### Forge Version:
1.10.2-12.18.3.2511

#### Describe the problem in repeatable steps:

1. Join a server
2. open fullscreen map, click "Use web browser"
3. The web browser will open and connect, but only player/entity markers will show. Terrain remains invisible. See https://gyazo.com/e10cf831f5640e16bb7ec557d50b4420

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

```[23:10:13] [Client thread/INFO] [JMLogger] JourneyMap log initialized.
[23:10:13] [Client thread/INFO] [JourneymapClient] initialize ENTER
[23:10:13] [Client thread/INFO] [?] Version: JourneyMap 1.10.2-5.5.2, built with Forge 12.18.3.2316
Forge: 12.18.3.2511
Environment: os.name, os.arch, java.version, user.country, user.language=null, game language=en_US, locale=en_us
Features: 
	RadarPlayers : singleplayer = true , multiplayer = true
	RadarAnimals : singleplayer = true , multiplayer = true
	RadarMobs : singleplayer = true , multiplayer = true
	RadarVillagers : singleplayer = true , multiplayer = true
	MapTopo : singleplayer = true , multiplayer = true
	MapSurface : singleplayer = true , multiplayer = true
	MapCaves : singleplayer = true , multiplayer = true
MiniMapProperties{state=Valid, file=journeymap.minimap.config, configVersion=5.5.2, zoomLevel=0, showPlayers=false, frameAlpha=100, compassFontScale=2, terrainAlpha=75, showEntityNames=false, enabled=true, showPlayerHeading=false, showVillagers=false, info2Label=Game Time, sizePercent=25, showDayNight=false, info3Label=Location, showMobs=false, showPets=false, preferredMapType=day, showCompass=true, mobDisplay=Large Dots, showReticle=true, orientation=My Heading, shape=Circle, showSelf=true, info4Label=Biome, locationFormat=xzy, playerDisplay=Large Dots, showGrid=true, reticleOrientation=My Heading, showWaypoints=true, showCaves=false, showAnimals=false, showMobHeading=false, showWaypointLabels=true, locationFormatVerbose=true, position=Top Right, info1Label=Blank, fontScale=2}
MiniMapProperties{state=Valid, file=journeymap.minimap2.config, configVersion=5.5.2, zoomLevel=0, showPlayers=false, frameAlpha=100, compassFontScale=1, terrainAlpha=75, showEntityNames=false, enabled=false, showPlayerHeading=false, showVillagers=false, info2Label=Game Time, sizePercent=25, showDayNight=false, info3Label=Location, showMobs=false, showPets=false, preferredMapType=day, showCompass=true, mobDisplay=Large Dots, showReticle=true, orientation=My Heading, shape=Circle, showSelf=true, info4Label=Biome, locationFormat=xzy, playerDisplay=Large Dots, showGrid=true, reticleOrientation=My Heading, showWaypoints=true, showCaves=false, showAnimals=false, showMobHeading=false, showWaypointLabels=true, locationFormatVerbose=true, position=Top Right, info1Label=Blank, fontScale=1}
FullMapProperties{state=Valid, file=journeymap.fullmap.config, configVersion=5.5.2, mobDisplay=Large Dots, zoomLevel=1, showPlayers=false, showSelf=true, locationFormat=xzyv, playerDisplay=Large Dots, showGrid=true, showEntityNames=true, showPlayerHeading=false, showVillagers=false, showWaypoints=true, showCaves=false, showAnimals=false, showMobHeading=true, showKeys=true, showWaypointLabels=true, locationFormatVerbose=true, showMobs=false, showPets=false, fontScale=2, preferredMapType=day}
WaypointProperties{state=Valid, file=journeymap.waypoint.config, configVersion=5.5.2, createDeathpoints=false, showName=true, maxDistance=0, autoHideLabel=false, showStaticBeam=true, minDistance=4, boldLabel=false, textureSmall=true, showDistance=true, showRotatingBeam=true, fontScale=2, showTexture=true, managerEnabled=true, beaconEnabled=true}
WebMapProperties{state=Valid, file=journeymap.webmap.config, configVersion=5.5.2, zoomLevel=0, showWaypoints=true, showCaves=false, showSelf=true, port=8080, showGrid=true, showEntityNames=false, enabled=true, googleMapApiDomain=.com, preferredMapType=day}
CoreProperties{state=Valid, file=journeymap.core.config, configVersion=5.5.2, verboseColorPalette=false, maxPlayersData=1, mapSurfaceAboveCaves=true, optionsManagerViewed=5.5.2, announceMod=false, colorPassive=#bbbbbb, renderOverlayEventTypeName=ALL, mapBlendWater=true, renderDistanceSurfaceMax=5, radarVerticalDistance=8, mapBlendGrass=true, recordCacheStats=false, hideSneakingEntities=true, revealShape=Circle, alwaysMapSurface=true, colorVillager=#88e188, mapPlants=false, colorPet=#0077ff, radarLateralDistance=16, mapBathymetry=true, mapCrops=true, maxMobsData=1, mapPlantShadows=false, alwaysMapCaves=true, checkUpdates=true, browserPoll=2000, mapBlendFoliage=true, mappingEnabled=true, colorPlayer=#ffffff, tileHighDisplayQuality=true, cacheVillagersData=1000, logLevel=INFO, maxVillagersData=1, maxAnimalsData=1, mapTransparency=true, tileRenderType=1, caveIgnoreGlass=true, mapTopography=true, renderDistanceCaveMax=6, mapAntialiasing=true, colorSelf=#0000ff, cachePlayersData=1000, cacheMobsData=1000, cachePlayerData=500, splashViewed=5.5.2, colorHostile=#ff0000, cacheAnimalsData=1000, themeName=OceanMonument, mapCaveLighting=true, renderDelay=2, renderOverlayPreEvent=true, autoMapPoll=2000}
[23:10:13] [Client thread/INFO] [ClientAPI] [ClientAPI] built with JourneyMap API 1.4
[23:10:13] [Client thread/INFO] [PluginHelper] Initializing plugins with Client API: journeymap.client.api.impl.ClientAPI
[23:10:13] [Client thread/INFO] [JourneymapClient] initialize EXIT, elapsed count 0 avg �ms
[23:10:30] [Client thread/INFO] [IconSetFileHandler] Added entity icons from journeymap:icon/entity. Success: false
[23:10:31] [Client thread/INFO] [ThemeLoader] Preloaded theme textures: 71
[23:10:31] [Client thread/INFO] [WebServer] Started webserver on port 8080
[23:10:32] [JM-VersionCheck-3/ERROR] [VersionCheck$1] Could not check version URL
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2
	at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[JsonParser.class:?]
	at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:131) [VersionCheck$1.class:1.10.2-5.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
	... 7 more
[23:11:25] [Client thread/INFO] [ColorManager] Loaded color palette for 1382 blockstates in 490ms
[23:12:31] [Client thread/INFO] [TopoRenderer] Loading journeymap.topo.config
[23:12:32] [Client thread/INFO] [WaypointStore] Loaded 0 waypoints from C:\Users\Fevix\AppData\Roaming\.minecraft\PokeBrawlers\journeymap\data\mp\Minecraft~Server\waypoints
[23:12:32] [Client thread/INFO] [JourneymapClient] Mapping started in C:\Users\Fevix\AppData\Roaming\.minecraft\PokeBrawlers\journeymap\data\mp\Minecraft~Server\DIM0. Memory: 3072MB total, 776MB free 
[23:29:53] [Client thread/WARN] [StatTimer] TileDrawStep.updateRegionTexture was slow: 64.69104 (Warning limit reached)
[23:29:53] [Client thread/WARN] [StatTimer] TileDrawStep.updateRegionTexture: Avg:        0ms, Min:        0ms, Max:     163.52ms, Total:          2 sec, Count:   505753, Canceled:        0, Slow:       10
[23:46:31] [Client thread/INFO] [StatTimer] TileDrawStep.updateRegionTexture hit max count, 1000000
[23:46:31] [Client thread/INFO] [StatTimer] TileDrawStep.draw(low) hit max count, 1000000
[00:37:52] [Client thread/INFO] [JourneymapClient] Mapping halted in C:\Users\Fevix\AppData\Roaming\.minecraft\PokeBrawlers\journeymap\data\mp\Minecraft~Server\DIM0
[00:48:12] [Client thread/INFO] [TopoRenderer] Loading journeymap.topo.config
[00:48:12] [Client thread/INFO] [WaypointStore] Loaded 0 waypoints from C:\Users\Fevix\AppData\Roaming\.minecraft\PokeBrawlers\journeymap\data\mp\Minecraft~Server\waypoints
[00:48:12] [Client thread/INFO] [JourneymapClient] Mapping started in C:\Users\Fevix\AppData\Roaming\.minecraft\PokeBrawlers\journeymap\data\mp\Minecraft~Server\DIM0. Memory: 4096MB total, 1958MB free 
[01:28:07] [Client thread/WARN] [StatTimer] TileDrawStep.updateRegionTexture was slow: 171.76032 (Warning limit reached)
[01:28:08] [Client thread/WARN] [StatTimer] TileDrawStep.updateRegionTexture: Avg:        0ms, Min:        0ms, Max:     171.76ms, Total:          3 sec, Count:   976672, Canceled:        0, Slow:       10
[01:29:04] [Client thread/INFO] [StatTimer] TileDrawStep.updateRegionTexture hit max count, 1000000
[01:37:29] [Client thread/INFO] [StatTimer] TileDrawStep.draw(low) hit max count, 1000000
[03:15:03] [Client thread/INFO] [JourneymapClient] Mapping halted in C:\Users\Fevix\AppData\Roaming\.minecraft\PokeBrawlers\journeymap\data\mp\Minecraft~Server\DIM0
[03:15:27] [Client thread/INFO] [TopoRenderer] Loading journeymap.topo.config
[03:15:28] [Client thread/INFO] [WaypointStore] Loaded 1 waypoints from C:\Users\Fevix\AppData\Roaming\.minecraft\PokeBrawlers\journeymap\data\mp\Minecraft~Server\waypoints
[03:15:28] [Client thread/INFO] [JourneymapClient] Mapping started in C:\Users\Fevix\AppData\Roaming\.minecraft\PokeBrawlers\journeymap\data\mp\Minecraft~Server\DIM0. Memory: 4096MB total, 1580MB free 
[03:31:21] [Client thread/WARN] [StatTimer] TileDrawStep.updateRegionTexture was slow: 230.502152 (Warning limit reached)
[03:31:22] [Client thread/WARN] [StatTimer] TileDrawStep.updateRegionTexture: Avg:     0.05ms, Min:        0ms, Max:      231.1ms, Total:          1 sec, Count:    33439, Canceled:        0, Slow:       10
```

#### Additional information that may be relevant: 
I'm using a 'side' profile with a custom minecraft location (Instead of `.minecraft/journeymap`, it's `.minecraft/profilename/journeymap`

**Comment by HenryLoenwind** [comment] 2018-03-31 00:39
btw, negative x is the issue. positive x works fine.

**Comment by aspirat2110** [comment] 2018-04-12 15:15
Same issue, only with with negative X. Positive X works

**Comment by BrainStone** [comment] 2018-04-14 00:37
I can confirm this issue.

**Comment by MCOfficer** [comment] 2018-05-01 12:30
confirmed with 1.12.2

**Comment by LokIsLoki** [comment] 2018-06-05 05:08
Can also reproduce this issue, positive X works fine

**Comment by meiskam** [comment] 2018-06-15 20:33
I noticed the problem as well, and fixed it .. Can't make a PR because there's no source here, but this is what I did:
problem was in file `\assets\journeymap\web\js\journeymap.js` in the `MCMapType.prototype.getTile` function after the line `zoom = Math.floor(zoom);` i've added this (replacing the existing tileUrl and tileId lines):
```
        var bound = 360 * Math.pow(2, zoom);
        var newX = (coord.x > bound/2) ? coord.x - bound : coord.x;

        var tileUrl = "/tile?zoom=" + zoom + "&x=" + newX + "&z=" + coord.y;
        var tileId = 'x_' + newX + '_y_' + coord.y + '_zoom_' + zoom;
```

**Comment by richardsgcooke** [comment] 2018-06-20 15:01
Also have this issue. 
https://i.imgur.com/fpqJ6Xf.png

**Comment by Quartzic** [comment] 2018-06-23 15:15
@meiskam's solution works perfectly, can we get this merged in?

**Comment by busheezy** [comment] 2018-09-05 16:34
I can't find the javascript file. Is the javascript hosted remotely now?

**Comment by smugleafdev** [comment] 2018-11-03 17:07
> I can't find the javascript file. Is the javascript hosted remotely now?

Go find the jar file at Curse\Minecraft\Instances\<unique>\mods\journeymap-1.12.whatever.jar and open it with 7zip, then find the js file at \assets\journeymap\ui\js and drag it to your desktop or wherever so you can modify it in Notepad++ or whatever program you use.

**Comment by xNxExOx** [comment] 2018-11-30 13:07
how to solve this in 5.5.2?

**Comment by rickybrent** [comment] 2019-01-27 05:18
meiskam's fix worked for me still; the line number changed but it was still the same part of the file. 👍

**Comment by mysticdrew** [comment] 2019-01-28 17:08
I have a private beta of 5.5.4 that hopefully resolves this issue. If you want to try it, ask in discord. I want it tested before I release it.

**Closed by mysticdrew** 2019-01-28 17:08 UTC
Labels: a:bug, in:webmap, jm:5.5.2, mc:1.10.2

**Comment by mysticdrew** [comment] 2019-02-24 16:43
@JLBShecky I fixed the -x issue. Please test beta 7.
