### ISSUE TITLE
[1.16.5] Visual bug of HUD

### ISSUE THREAD

**Issue by DoctorSigma** [TeamJM/journeymap#462] opened 2022-06-18 09:15 UTC
#### JourneyMap Version:
journeymap-1.16.5-5.8.5p4

#### Forge Version:
36.2.34

#### Describe the problem in repeatable steps:
When I updated the version of JourneyMap from 5.8.3 to 5.8.5p4 there was a problem as in the screenshot below, ie the whole HUD (I don't really remember what it's called):
![image](https://user-images.githubusercontent.com/93322905/174431112-8b0f0508-6280-4ddd-8ea7-4c3f76d7d508.png)
As for the steps to reproduce it, I did not find any patterns, just flew around the world in my modpack, I will also attach the modpack profile.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/8933268/journeymap.log)
[1.16.5_MOD_100Plus-18.06.2022.zip](https://github.com/TeamJM/journeymap/files/8933270/1.16.5_MOD_100Plus-18.06.2022.zip)

**Comment by mysticdrew** [comment] 2022-06-18 11:35
did you update other mods aswell? Does reverting back to  5.8.3 resolve it?
I see you have at least one other mod that interacts with the hud.

**Comment by DoctorSigma** [comment] 2022-06-18 11:37
So I changed the versions of other mods. Almost half of the modifications were removed by xD. But the return to version 5.8.3 helped

**Comment by mysticdrew** [comment] 2022-06-20 21:15
Fixed in 5.8.5p5

**Closed by mysticdrew** 2022-06-20 21:15 UTC

**Comment by Mitchell5200** [comment] 2022-08-26 14:39
This also seems to be a randomly occurring issue on 1.18.2 with `journeymap-1.18.2-5.9.0beta1-forge`, i've not confirmed it on `beta2` however, due to the unpredictable nature of the bug

![2022-08-26_20 56 48](https://user-images.githubusercontent.com/45913837/186927050-cc8299b2-21ee-4d70-90e1-94de500d8ed4.png)

**Comment by mysticdrew** [comment] 2022-08-26 14:42
> This also seems to be a randomly occurring issue on 1.18.2 with `journeymap-1.18.2-5.9.0beta1-forge`, i've not confirmed it on `beta2` however, due to the unpredictable nature of the bug
> 
> ![2022-08-26_20 56 48](https://user-images.githubusercontent.com/45913837/186927050-cc8299b2-21ee-4d70-90e1-94de500d8ed4.png)

This issue is unrelated to the OP as it is a completely different version. However, it is in fact fixed in beta2.

**Comment by Mitchell5200** [comment] 2022-08-26 14:44
> > This also seems to be a randomly occurring issue on 1.18.2 with `journeymap-1.18.2-5.9.0beta1-forge`, i've not confirmed it on `beta2` however, due to the unpredictable nature of the bug
> > ![2022-08-26_20 56 48](https://user-images.githubusercontent.com/45913837/186927050-cc8299b2-21ee-4d70-90e1-94de500d8ed4.png)
> 
> This issue is unrelated to the OP as it is a completely different version. However, it is in fact fixed in beta2.

Oh okay thank you.
