### ISSUE TITLE
[1.12.2] Client lockup/hang on dimension change

### ISSUE THREAD

**Issue by MatthiasMann** [TeamJM/journeymap#100] opened 2019-04-09 10:07 UTC
#### JourneyMap Version:
journeymap-1.12.2-5.5.4

#### Forge Version:
1.12.2-14.23.5.2824

#### Describe the problem in repeatable steps:
After switching dimensions using the waystones mod from the aroma1997's mining dimension to the over world the client locked up:
[journeymap_lockup.log](https://github.com/TeamJM/journeymap/files/3058297/journeymap_lockup.log)

I was running the 'Only missing' mapping command before changing the dimension inside the mining dimension 

I have changed dimensions using this way many times before - so it's a random crash or related to running the mapping before. This is the first time I had such a hang.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/3058313/journeymap.log)

**Comment by mysticdrew** [comment] 2019-04-09 20:26
Do you mean this?
You started auto-map as "only missing" you then jumped in a portal to a new dimension before it was finished auto-mapping?

**Comment by MatthiasMann** [comment] 2019-04-09 20:32
I'm not sure if it was finished or not - when I click "generate missing" the area around my player goes "black" in the full screen map for a few seconds before it reappears in big squares. It is possible that I jumped through the portal / waystone when ~3 of the squares appeared. I was only looking if the area around the village I was in appeared.

**Comment by mysticdrew** [comment] 2019-04-09 20:35
Can you see if you can replicate it please? It's likely it was not finished. The automap is a fairly computational expensive operation. I am sure lots of things will go crazy if you change dimensions while it is happening. It is advised you wait for it to finish before doing anything.

**Comment by MatthiasMann** [comment] 2019-04-09 21:14
I tried to reproduce it twice - even with "all" instead of "missing" but it did not lock up again. Here is the latest log file:
[journeymap.log](https://github.com/TeamJM/journeymap/files/3061010/journeymap.log)

**Comment by mysticdrew** [comment] 2019-04-09 23:09
Interesting, though to be honest. The initial journeymap_lockup.log seemed more like a java issue error. 

I am going to close this as an external issue. I will reopen it if we can find a way to consistently reproduce it.

**Comment by MatthiasMann** [comment] 2019-04-10 06:00
From the jstack output it looks like this:
The client thread is holding the lock 0x00000004e2d5f2d8 and then waits for a future which I assume is either of the JM-Thread-XX features. But these can't complete as the lock is hold.

This is a clear dead lock scenario - but I never had one involving features.
My suggestion would be to not execute tasks while holding the task queue lock in MainTaskController.

**Comment by mysticdrew** [comment] 2022-01-17 23:16
So an update, I spent a significant amount of time trying to replicate this issue so I can fix it in later versions as 1.12.2 has been EOL for some time now.

I have been unable to replicate it, by teleporting and switching dimensions when automapping. There have been improvements in the threading since this issue happened so maybe it resolved with that. 

I am closing this to cleanup the issue tracker.

**Closed by mysticdrew** 2022-01-17 23:16 UTC
Labels: mc:1.12.2, jm:5.5.4
