### ISSUE TITLE
[1.12.2] Map not switching back to surface mode after going in cave mode

### ISSUE THREAD

**Issue by Mexicanplayer97** [TeamJM/journeymap#24] opened 2018-01-20 23:17 UTC
#### JourneyMap Version: 1.12.2 - 5.6.0b2

#### Describe the problem in repeatable steps:

1.Enter a cave or underground for cave mode
2.When returning to surface, Map does not return to surface mode and requires re-launch to fix
3.Has happened every time I play the moment I go in caves

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
no errors in log
![2018-01-20_16 54 14](https://user-images.githubusercontent.com/35642723/35188923-978dd9be-fe05-11e7-9298-34c07b21c27c.png)
![2018-01-20_16 55 47](https://user-images.githubusercontent.com/35642723/35188924-98ef846a-fe05-11e7-93f2-94aa26b54415.png)
Pictures for more detail specs

**Comment by BrainStone** [comment] 2018-01-27 22:38
Duplicate of #13

**Closed by BrainStone** 2018-01-27 22:38 UTC
Labels: a:bug, in:client, jm:5.6.0, mc:1.12.2, status:duplicate
