### ISSUE TITLE
[Bug]: Crash after remove death waypoint

### ISSUE THREAD

**Issue by Rumaruka** [TeamJM/journeymap#786] opened 2024-09-06 09:50 UTC
### What happened?

Crash in Client Side

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[crash-2024-09-06_14.47.01-client.txt](https://github.com/user-attachments/files/16906072/crash-2024-09-06_14.47.01-client.txt)
[journeymap.log](https://github.com/user-attachments/files/16906078/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16906082/latest.log)

**Comment by mysticdrew** [comment] 2024-09-06 13:04
Thanks, I see what the issue is. 
Will be fixed for the next release. Are you playing Lan by chance?

**Comment by Rumaruka** [comment] 2024-09-06 15:00
If you mean enable "Open for Lan" 
 yes, it's enabled

**Comment by mysticdrew** [comment] 2024-09-06 16:05
Ahh okay, thanks. That is helpful, fix will hopefully be out today.

**Comment by mysticdrew** [comment] 2024-09-06 17:15
journeymap 1.21-6.0.0-beta.24

**Closed by mysticdrew** 2024-09-06 17:15 UTC
Labels: a:bug
