### ISSUE TITLE
[1.12.2] Server log spam with exception messages whenever teleporting to another dimension

### ISSUE THREAD

**Issue by Fatmice** [TeamJM/journeymap#57] opened 2018-06-22 09:46 UTC
#### JourneyMap Version:
JourneyMap 1.12.2-5.5.2, built with Forge 14.23.0.2491

#### Forge Version:
forge-1.12.2-14.23.4.2705-universal

#### Describe the problem in repeatable steps:

1. Run server with SpongeForge-1.12.2-2705-7.1.0-BETA-3218
2. Teleport to another dimension using a tool like RFtool
3. Server log should get spam with exceptions

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
Server side log

```
[09:36:11] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
        at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
        at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1042_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1205) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
        at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:376) [pl.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:165) [pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:72) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 28 more
[09:36:11] [Server thread/INFO] [projecte]: Sent knowledge and bag data to MoMuffins
[09:36:11] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[09:36:11] [Server thread/INFO] [mcjty.lib.varia.Logging]: SMP: Player logged in: Sync diminfo to clients
[09:36:11] [Server thread/INFO] [mcjty.lib.varia.Logging]: Send dimlet rules to the client
[09:36:11] [Server thread/INFO] [mcjty.lib.varia.Logging]: Rules packet size: 5779 of 8192
[09:36:11] [Server thread/INFO] [Mekanism]: Sent config to 'MoMuffins.'
[09:36:11] [Server thread/INFO] [journeymap]: Sending log in packet.
[09:36:12] [Server thread/INFO] [Astral Sorcery]: [AstralSorcery] Synchronizing configuration to MoMuffins
[09:36:12] [ForkJoinPool-1-worker-11/INFO] [opencomputers]: Starting OpenComputers version check.
[09:36:12] [ForkJoinPool-1-worker-11/INFO] [opencomputers]: Running the latest OpenComputers version.
[09:36:42] [Server thread/INFO] [journeymap]: MoMuffins joining dimension 4
[09:36:42] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
        at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
        at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1042_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1205) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
        at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:721) [pl.class:?]
        at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:623) [pl.class:?]
        at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:610) [pl.class:?]
        at mcjty.lib.varia.TeleportationTools.teleportToDimension(TeleportationTools.java:62) [TeleportationTools.class:?]
        at mcjty.rftools.blocks.teleporter.TeleportationTools.performTeleport(TeleportationTools.java:144) [TeleportationTools.class:?]
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.performTeleport(MatterTransmitterTileEntity.java:538) [MatterTransmitterTileEntity.class:?]
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.checkStateServer(MatterTransmitterTileEntity.java:377) [MatterTransmitterTileEntity.class:?]
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.func_73660_a(MatterTransmitterTileEntity.java:320) [MatterTransmitterTileEntity.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1832) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:72) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 31 more
[09:36:42] [Server thread/WARN] [io.netty.channel.embedded.EmbeddedChannel]: More than one exception was raised. Will report only the first one and log others.
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
        at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
        at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1042_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1205) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
        at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:721) [pl.class:?]
        at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:623) [pl.class:?]
        at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:610) [pl.class:?]
        at mcjty.lib.varia.TeleportationTools.teleportToDimension(TeleportationTools.java:62) [TeleportationTools.class:?]
        at mcjty.rftools.blocks.teleporter.TeleportationTools.performTeleport(TeleportationTools.java:144) [TeleportationTools.class:?]
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.performTeleport(MatterTransmitterTileEntity.java:538) [MatterTransmitterTileEntity.class:?]
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.checkStateServer(MatterTransmitterTileEntity.java:377) [MatterTransmitterTileEntity.class:?]
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.func_73660_a(MatterTransmitterTileEntity.java:320) [MatterTransmitterTileEntity.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1832) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:72) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 31 more
```

**Comment by fscan** [comment] 2018-06-26 22:45
Also happens without sponge

**Comment by Fatmice** [comment] 2018-06-27 02:33
Fresh logs
Running SpongeForge v1.12.2-2705-7.1.0-BETA-3235
[logs.zip](https://github.com/TeamJM/journeymap/files/2139619/logs.zip)

**Comment by Weissmoon** [comment] 2018-07-07 10:14
This is a duplicate of #42.

**Closed** 2018-07-07 12:39 UTC
Labels: a:bug, in:server, jm:5.5.2, mc:1.12.2, status:duplicate
