### ISSUE TITLE
[Feature Request]: sync map with other players

### ISSUE THREAD

**Issue by juster-0** [TeamJM/journeymap#722] opened 2024-06-14 20:05 UTC
### Describe the new feature.

I think it will be cool if it was possible to sync map (without waypoints) with other players on a server. I think it’s possible to implement if the mod is installed on the server.

Additionally to that I think it’s possible to add functionality to add “global” waypoints that will be controlled by server admins and will be synced with other players.

**Comment by mysticdrew** [comment] 2024-06-17 15:19
map sync duplicate of 
https://github.com/TeamJM/journeymap/issues/419

global waypoints are already planned.

**Closed by mysticdrew** 2024-06-17 15:19 UTC
Labels: a:enhancement
