### ISSUE TITLE
[1.12.2] Waypoints disappear after playing on LAN

### ISSUE THREAD

**Issue by fgRuslan** [TeamJM/journeymap#109] opened 2019-05-19 11:55 UTC
#### Describe the problem in repeatable steps:

1. After connecting to somebody in LAN, waypoints and discovered map disappear.
2. If you leave and join the game, everything is okay, but if the person you are connected to leaves the game, the next time you join this person's world, you will have your waypoints and previously discovered map lost. This person's waypoints and discovered map will be okay.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No errors in the log file.

**Comment by mysticdrew** [comment] 2019-05-19 23:53
Can you see if this is an issue with 5.5.4 also please?

**Comment by fgRuslan** [comment] 2019-05-22 10:47
I have checked this on 5.5.4 while my friend had the 5.5.5b version and I still have got this issue.

**Comment by fgRuslan** [comment] 2019-05-27 17:43
I asked my friend to download 5.5.4. Now we both have 5.5.4 and this is still an issue.

**Comment by JonathanPlovie** [comment] 2019-06-05 10:31
I have the same issue. Playing on a solo SP world that I'm hosting myself because I want to run a few server side mods. Waypoints I make during my session are gone the next time I host my server and enter the game.

**Comment by mysticdrew** [comment] 2020-01-20 02:45
I tired to reproduce this but could not. Closing, though I did fix some other lan related bugs.

**Closed by mysticdrew** 2020-01-20 02:45 UTC
Labels: a:bug, in:client, jm:5.5.5, mc:1.12.2
