### ISSUE TITLE
[1.15.2] Lag from Journeymap

### ISSUE THREAD

**Issue by Darkere** [TeamJM/journeymap#189] opened 2020-03-15 20:26 UTC
#### JourneyMap Version:

journeymap-1.15.2-5.7.0beta1.jar

#### Forge Version:

forge 31.1.19

![image](https://user-images.githubusercontent.com/4283717/76709956-77c23300-6703-11ea-9bc4-b1b862928511.png)

https://sparkprofiler.github.io/#R4TlMIBCkC

**Comment by mysticdrew** [comment] 2020-03-15 20:43
More details

**Comment by Darkere** [comment] 2020-03-15 20:48
Not sure what you want me to elaborate on. Spark shows that the game is spending 27% of the time in the server thread on the SendPlayersOnRadarToPlayers method. That's a massive amount of time double the amount of time spent on entities.

**Comment by mysticdrew** [comment] 2020-03-18 17:52
You need to elaborate on the `lag`.

**Comment by Darkere** [comment] 2020-03-18 18:00
Yes, tps was significantly reduced.

**Comment by mysticdrew** [comment] 2020-03-18 18:16
In the server admin screen, what is your expanded radar set to?

**Comment by Darkere** [comment] 2020-03-18 18:35
We did not change any settings from default before putting it on our servers. We have since removed Journeymap from the server so I do not know. Accessing the admin screen crashes when journey map is not installed on the server (or so I've heard would need to confirm).

**Comment by mysticdrew** [comment] 2020-03-18 19:04
Well, if you can confirm please let me know and get me a crash report for it so I can fix it. 
I cannot fix things that are not reported. 
Keep in mind this is a very early beta so there is bound to be a lot of bugs, I am slowly squashing them. 

How many players did you have on your server when you noticed the lag?

**Comment by Darkere** [comment] 2020-03-18 19:36
We had 18 players on the server at the time.

**Comment by mysticdrew** [comment] 2020-03-18 19:52
Did you have a similar 1.12.2 server with the same amount of people and it did not cause an issue?

I figured that expanded radar would be a little heavy on servers with a larger player base, but not enough to bring tps down. That is why I set the slider for how often to update so larger servers can slow down the update time.

You can disable expanded radar and then it will bring tps back to normal. Looks like I need to optimize more.

**Comment by mysticdrew** [comment] 2020-03-23 18:02
> We had 18 players on the server at the time.
> 
> Also seems like the crash issue is already fixed. The button for the admin panel is not there anymore when on a server without JM installed.

yes, that is intentional. Cannot control server settings when the mod is not on the server.

**Comment by cowpod** [comment] 2020-04-03 23:22
Lag occurs for me in Single player (and LAN). Without Journeymap I get an average of 180FPS. With it and default settings I get 45FPS. On slower computers this is a lot more extreme.
Unchecking radar for players/mobs/etc in the admin panel gains an additional ~20FPS. I've looked for an option to completely disable radar or Advanced Radar but haven't found it.

1.15.2, 5.7.0beta1

**Comment by mysticdrew** [comment] 2020-04-04 00:05
Is this Network Lag, or FPS Drop? They are completely different, I can address the network lag by optimizing how things are sent between the server and client. But there is not much that can be done about fps drop other than you tweaking the settings in journeymap. There are a lot of options in there to deal with slow computers.

**Comment by mysticdrew** [comment] 2020-04-04 00:06
> Lag occurs for me in Single player (and LAN). Without Journeymap I get an average of 180FPS. With it and default settings I get 45FPS. On slower computers this is a lot more extreme.
> Unchecking radar for players/mobs/etc in the admin panel gains an additional ~20FPS. I've looked for an option to completely disable radar or Advanced Radar but haven't found it.
> 
> 1.15.2, 5.7.0beta1, forge 31.1.35
> 
> tested with only journeymap (no other mods), same issue.

if you disabled all the individual radars, then radar is disabled....

**Comment by cowpod** [comment] 2020-04-04 02:12
i7-8750H, RTX2070 -  Without journeymap I consistently get above 100 FPS, but with it I rarely get more than 50. 
I guess radar isn't the only feature causing lag? I've lowered the cartography range to 3, but doesn't seem to affect much.

**Comment by kbulgrien** [comment] 2020-04-17 22:26
FWIW, I used JourneyMap a long time on 1.12 but then lost use of it after updating.  I recently found the Beta for 1.14.  It has the same issue, so I do not think this is unique to 1.15.  With JourneyMap loaded on the client, the game is practically unplayable because the lag is so bad.  It "feels" like server lag, but players running a client with out the JourneyMap mod are unaffected.  It plays kind of like trying to run in water...

**Comment by FeuFeve** [comment] 2020-04-27 23:47
I5-6600k, GTX980Ti, 16Gb of RAM with 4/6/8Gb allowed to the game (tried the 3).
I have the same issue with JourneyMap in the current 1.14.4 version.

I made a custom modpack and was constantly freezing, so I tried removing different mods and it seems like JourneyMap was the cause (enabled, the game is unplayable, without it I'm over 100-150 fps most of the time).

After some tries:
- With JourneyMap as the **only mod loaded**, the game works correctly
- If I add Optifine, the lags come back
- With all the mods and **either JourneyMap or Optifine**, the game works correctly

Using:
- Forge 28.2.0 (recommended build for 1.14.4)
- OptiFine 1.14.4 HD U F5
- JourneyMap 1.14.4 5.7.0b1

**Comment by marcebdev** [comment] 2020-05-10 05:13
Will try to reconfirm tomorrow but I’m quite sure it is a network issue, I haven’t played much SP to compare but on MP the server was given more than enough resources and still hiccups (even to me on localhost) it’s periodic but annoying. I’d have to also fully test without the mod as well but given this issue is here its very likely related.

**Comment by marcebdev** [comment] 2020-05-10 05:20
@cowpod @FeuFeve its odd you’re getting a magnitude higher FPS without the mod alone since I’m under the impression it’s more network or server related. However, you may want to check you’re using GPU and not integrated graphics as I’m easily running 144FPS locked with 2Gb dedicated and other mods.

The difference between allowing Minecraft GPU resources is night and day likely especially due to the vram. There should be no reason pretty much ever to need > 6Gb ram and even usually > 4Gb having too much can actually cause adverse effects with the garbage collector for vanilla I wouldn’t do anything over 2Gb (I’m running that right now with some other mods and JM) again 0 problems. I also have a 3700X & 1070 so there’s no way you’re system is holding you back.

**Comment by mysticdrew** [comment] 2020-06-16 17:49
1.15.2 memory leak was fixed in 5.7.0 beta 3, the optifine 1.14.4 issue was fixed in beta 2. Closing

**Closed by mysticdrew** 2020-06-16 17:49 UTC
Labels: a:bug, in:client, jm:5.7.0, mc:1.15.2
