### ISSUE TITLE
[1.19.2] atm8 modpack, friend not showing on mini map and cartography doesnt discover new area

### ISSUE THREAD

**Issue by Gayanfalor** [TeamJM/journeymap#533] opened 2022-12-05 07:38 UTC
#### JourneyMap Version:

journeymap-1.19.2-5.9.0beta3-forge

#### Forge Version:

43.1.55

#### Describe the problem in repeatable steps:

1.play with some friends
2. maybe do some dimmension teleport
3.and sometime your friends doesnt show on the minimap and also the cartography doesnt reveal  undiscovered map on the mini map letting just black square

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

i  dont think there is, i'll look after i get the problem, here the log is empty as i relaunched the game

[2022-12-04-7.log](https://github.com/TeamJM/journeymap/files/10151667/2022-12-04-7.log)

**Comment by mysticdrew** [comment] 2022-12-05 12:16
"also the cartography doesnt reveal undiscovered map on the mini map letting just black square" 
What does this mean, do you have a screenshot?
" sometime your friends doesnt show on the minimap "
Players only show up when they are within your render range. 

You have a lot of mod errors in your pack, you also do not have enough memory assigned to minecraft. I see several out of memory errors. ATM Requires a lot of memory.

**Comment by Gayanfalor** [comment] 2022-12-05 17:40
> "also the cartography doesnt reveal undiscovered map on the mini map letting just black square"
> What does this mean, do you have a screenshot?
you know when you explore the world on the minimap it "draws" it on the minimap, well then here its not, the mini map stays empty.

> " sometime your friends doesnt show on the minimap "
> Players only show up when they are within your render range.
he is but its not shown i need to open and close the world map and close it and after i see him on the mini map.

I allowed 8196mb of ram to minecraft i cant give more as it already at 100% use after a bit on the game.

I also sometime the game froze when opening the world map, i get the windows cursor as its searching but it doesnt and i kill the minecraft process

**Comment by mysticdrew** [comment] 2022-12-05 17:44
Well, you have some out of memory errors in your logs. This is likely due to the size of ATM pack. They are likely not related to journeymap but can cause a whole host of issues. 

My first suggestion is to delete the ./minecraft/journeymap/config folder and restart minecraft to regenerate the configs. Do not delete anything else in the journeymap directory.  See if this fixes some of your issues.

**Comment by Gayanfalor** [comment] 2022-12-05 17:54
well i can try that thanks

**Comment by mysticdrew** [comment] 2022-12-05 18:53
you will need to provide your jouneymap.log and latest.log

**Comment by Utlamo** [comment] 2022-12-07 11:51
I see in my case the problem is file C:\Users\Utlamo\AppData\Roaming\.minecraft\journeymap\config\5.9\journeymap.core.config
and option "mappingEnabled": "false",

**Comment by Gayanfalor** [comment] 2022-12-10 08:13
oh sorry i ddint seen you were waiting  for info, do i need to close the game to get the journeymap.log ? as i am connected on the game when i look in the folder it's empty

**Comment by mysticdrew** [comment] 2022-12-10 17:38
This is really odd. 
So you have a bad block somewhere and it is causing a failure in our caching system which in turn breaks mapping for some reason. (I think this is what is happening)

Can you come into our discord, head to the #jm-support channel and create new post, please read the READ FIRST post so your post does not get automatically deleted. 

I am going to have you try some test builds to see if we can resolve the mapping issue first, then we can tackle the unable to see your friends.

**Comment by mysticdrew** [comment] 2022-12-11 23:58
Issue was found and addressed, fix will be in the next release. I will comment and close this ticket when the release is published

**Closed** 2022-12-22 16:31 UTC
Labels: a:bug, status:fixed, in:client, status:completed
