### ISSUE TITLE
[1.19.2] Fabric - Oh the Biomes you Go flowers rendered as black dots

### ISSUE THREAD

**Issue by DracoExE** [TeamJM/journeymap#496] opened 2022-08-26 20:50 UTC
#### Describe the problem in repeatable steps:

1. Create a new world using the Oh the Biomes you'll Go
2. Search the Amaranth fields region
3. Activate the render plants option in JourneyMap
4. Check plants rendered in minimap and large map

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No relevant errors from the log

#### Other details that might help

Modded tree leaves and blocks render with the current colors correctly.

Here're some images of the issue. As you can see, the flowers from the mod are varied and they have lots of colors, but they're all rendered as black dots, while vanilla plants are rendered correctly.

![2022-08-26_16 35 20](https://user-images.githubusercontent.com/44948988/186988038-d8241615-a89a-430a-8c4b-0e5f76b11668.png)

![2022-08-26_16 33 45](https://user-images.githubusercontent.com/44948988/186988035-e6be4795-939e-400e-9eab-cb97c82ddc08.png)

No idea if this happens with plants from other mods, might be interesting to check that too

**Comment by mysticdrew** [comment] 2022-08-26 20:52
I will need to add an exception to not render these flowers.

**Comment by mysticdrew** [comment] 2022-08-26 21:15
you may be able to fix it by disabling the plant option in the cartography settings.

**Comment by DracoExE** [comment] 2022-08-26 21:47
> you may be able to fix it by disabling the plant option in the cartography settings.

Disabling the option removes all the black dots, yes, but it also removes vanilla flowers dots in the map (which are colored correctly in the map)

I also tested by disabling and enabling the option in the cartography settings, but it keeps rendering the modded flowers as black dots and vanilla flowers correctly.

Some other testing I just did: 
- Looks like all flowers from the ByG mod causes this issue, but other plant-like blocks from the mod such as beach grass, cattail sprouts and prairie grass have their colors rendered correctly.
- I also tested the rainbow flower from the Blockus mod and the void lily from the Bosses of Mass Destruction mod, and they also are rendered as a black dots, so it seems it's a more general bug related to any modded flower

home this information also helps!

**Comment by mysticdrew** [comment] 2022-08-27 00:25
It's not a bug, it's how the mods color the flowers. I need to handle them a special way. 

The colors are derived from the texture color, but those flowers all have the same texture.

**Comment by mysticdrew** [comment] 2022-12-07 21:26
Fixed for next release. 1.19.3 and 1.18.2 versions for both forge and fabric. 
This fix should resolve blocks for other mods too. 
I will close this ticket when release is published

**Comment by mysticdrew** [comment] 2022-12-08 15:05
This issue is resolved and in beta for for 1.18.2 and 1.19.3 for both fabric and forge. 
Download here:
https://www.curseforge.com/minecraft/mc-mods/journeymap/files
https://modrinth.com/mod/journeymap/versions

**Closed by mysticdrew** 2022-12-08 15:05 UTC
Labels: status:fixed, in:client, status:completed, a:mod-interaction, loader:fabric
