### ISSUE TITLE
[Crash]: compatibility error with NBT Editor

### ISSUE THREAD

**Issue by the456gamer** [TeamJM/journeymap#575] opened 2023-03-12 22:31 UTC
### What happened?

When opening the full screen map with "j", the game crashed instead of opening the map

tested in a single player world with
[NBT Editor 1.10.0 ](https://modrinth.com/mod/nbt-editor)

https://github.com/mega12345mega/NBT-Editor/issues/40

### Minecraft Version

1.19.3+(Default)

### Version

5.9.3 (Default)

### Relevant log output

https://gist.github.com/the456gamer/389ae6fb4d0744980fb883a250a9ecba

**Comment by mysticdrew** [comment] 2023-03-13 00:42
This is really odd, they may be doing something funny with mixins. 
I can probably put in a protection usecase to not throw an exception, but I will have to dig in when I get time. Thanks

**Comment by mega12345mega** [comment] 2023-03-13 05:48
I haven't decompiled the mod to check, but I'm guessing this is caused by [this](https://github.com/mega12345mega/NBT-Editor/blob/9f4b9fe1736b2ca1342f0e97c9c3199b30b4dd47/src/main/java/com/luneruniverse/minecraft/mod/nbteditor/mixin/source/ScreenMixin.java#L26) mixin. This has caused [other](https://github.com/mega12345mega/NBT-Editor/issues/34) incompatibilities with other mods, so this seems likely. I'm planning to change the logic to where `CreativeTab.CreativeTabGroup` isn't added unless it contains tabs, which should solve the problem (assuming this is the issue). I've been a bit busy, but I might be able to release an update sometime after 1.19.4 comes out, since it is sure to break something.

**Comment by mysticdrew** [comment] 2023-03-13 21:07
> I haven't decompiled the mod to check, but I'm guessing this is caused by [this](https://github.com/mega12345mega/NBT-Editor/blob/9f4b9fe1736b2ca1342f0e97c9c3199b30b4dd47/src/main/java/com/luneruniverse/minecraft/mod/nbteditor/mixin/source/ScreenMixin.java#L26) mixin. This has caused [other](https://github.com/mega12345mega/NBT-Editor/issues/34) incompatibilities with other mods, so this seems likely. I'm planning to change the logic to where `CreativeTab.CreativeTabGroup` isn't added unless it contains tabs, which should solve the problem (assuming this is the issue). I've been a bit busy, but I might be able to release an update sometime after 1.19.4 comes out, since it is sure to break something.

looks like that clearChildren mixin is probably the cause of the issue. I tried to dig in a bit to see what was going on, but our mods are not compatible indev due to naming collisions since we are mojangmap, you use yarn and use some mojangmap names. It breaks things indev for me. 

```
  METHODs com/luneruniverse/minecraft/mod/nbteditor/multiversion/MultiVersionScreen/[onClose, net/minecraft/class_437/method_25419]()V -> onClose
  METHODs com/luneruniverse/minecraft/mod/nbteditor/multiversion/MultiVersionScreen/[isPauseScreen, net/minecraft/class_437/method_25421]()Z -> isPauseScreen
  METHODs com/luneruniverse/minecraft/mod/nbteditor/screens/ClientContainerScreen/[onClose, net/minecraft/class_437/method_25419]()V -> onClose
  METHODs com/luneruniverse/minecraft/mod/nbteditor/screens/ClientContainerScreen/[isPauseScreen, net/minecraft/class_437/method_25421]()Z -> isPauseScreen
There were unfixable conflicts.
```

**Comment by mysticdrew** [comment] 2023-03-13 22:18
I removed that mixin from the jar and JourneyMap did not crash, so that is likely the case.

**Comment by mysticdrew** [comment] 2023-04-01 21:21
This is fixed for the unreleased version of NBT Editor. 
I am closing this, please track the issue on their issue tracker. 
Thanks @mega12345mega

**Closed by mysticdrew** 2023-04-01 21:21 UTC
Labels: waiting-for:external, a:mod-interaction, a:crash
