### ISSUE TITLE
[1.16.5] Invalid teleportation coordinates in Nether

### ISSUE THREAD

**Issue by WhatIsLowe** [TeamJM/journeymap#374] opened 2022-01-12 10:26 UTC
**JourneyMap Version: 1.16.5-5.7.3**

#### Describe the problem in repeatable steps:

1. I select a label with the given coordinates:
![image](https://user-images.githubusercontent.com/37247729/149122139-9c77b256-ba34-4d25-b6a9-63d2af8c66f2.png)
2. But it teleports me to these coordinates:
![image](https://user-images.githubusercontent.com/37247729/149122577-ae8170d1-a1c1-46cf-9f68-85dbde1924cc.png)

Strange, but in the Overworld everything works fine

P.S. I opened the json file of the waypoint and the XYZ-coordinates do not match those on which I put the waypoint and which are indicated in the first picture...
`{
  "id": "Крепость 2_4944,38,1960",
  "name": "Крепость 2",
  "icon": "waypoint-normal.png",
  "x": 4944,
  "y": 38,
  "z": 1960,
  "r": 75,
  "g": 97,
  "b": 167,
  "enable": true,
  "type": "Normal",
  "origin": "journeymap",
  "dimensions": [
    "minecraft:the_nether"
  ],
  "persistent": true,
  "showDeviation": false
}`

**Comment by uecasm** [comment] 2022-01-12 10:34
Probably a duplicate of #319

**Comment by mysticdrew** [comment] 2022-01-12 11:49
Update to 5.8.0 beta

**Closed by mysticdrew** 2022-01-12 11:49 UTC
