### ISSUE TITLE
[Bug]: In game text becomes obscured with black boxes

### ISSUE THREAD

**Issue by 5050Shauna** [TeamJM/journeymap#851] opened 2024-12-31 11:16 UTC
### What happened?

While playing I have noticed an error where occasionally all my in game text becomes obscured with black boxes as seen in the pictures below. 

Reloading my textures temporarily resolves the problem but after a while it returns.

The only mod I have installed is JourneyMaps
![2024-12-31_10 51 19](https://github.com/user-attachments/assets/091f3f59-2d5a-49bc-b18b-e26710f84396)
![2024-12-31_10 51 21](https://github.com/user-attachments/assets/45d8e20b-215d-485e-8572-274b0727ac00)

### Mod Loader

Fabric

### Minecraft Version

1.21.4

### Version

6.0.0-beta.x - Specify Beta version

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/18281068/journeymap.log)
[latest.log](https://github.com/user-attachments/files/18281071/latest.log)

**Comment by mysticdrew** [comment] 2024-12-31 16:45
come into our discord please. I have been unable to replicate this issue. I have an indev version I need someone with this issue to see if it fixes it.

**Comment by mysticdrew** [comment] 2024-12-31 16:46
closing this issue as it is a duplicate of 
https://github.com/TeamJM/journeymap/issues/834
Please continue in that issue.

**Closed by mysticdrew** 2024-12-31 16:46 UTC
Labels: a:bug
