### ISSUE TITLE
[Suggestion]: Re-Add Vault theme

### ISSUE THREAD

**Issue by BastardNeko** [TeamJM/journeymap#619] opened 2023-07-12 00:43 UTC
### What happened?

Is this a bug? or was it just never updated to the latest versions? I really wanted to use it on 1.20.1
JM Version is 5.9.11

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

other (please list)

**Comment by mysticdrew** [comment] 2023-07-12 00:48
It was removed in 1.12.2 versions of journeymap for some reason, I have no idea why it was not ported over to the new theme template. 
However, it is already ported for the next major version of journeymap, Journeymap 6.0.0 when it is released, not anytime soon as it is a major rewrite of many systems though. 

This is not a bug, i will fix that. Keep an eye on this issue, i will close it when there is a public version of JM6

**Comment by mysticdrew** [comment] 2024-01-17 22:45
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.

**Closed by mysticdrew** 2024-01-17 22:45 UTC
Labels: a:enhancement, status:completed, jm:6.0.x
