### ISSUE TITLE
[Feature Request] The ability to add Extra Themes (instead of replacing existing ones)

### ISSUE THREAD

**Issue by SextupleTap** [TeamJM/journeymap#86] opened 2019-01-24 14:16 UTC
As of now the Themes present in JourneyMap are the biome themes, which replaced the older themes such as "purist" etc.

Also as of now you are still only capable of 'Modifying Existing Themes' to make a custom theme. However, it would be nice if the mod gained the functionality for you to be able to just add in your own theme instead of overwriting an existing one.

**Comment by mysticdrew** [comment] 2019-12-16 01:18
This is a bug, you should be able to create custom themes. 
Closing as a duplicate of #140

**Closed by mysticdrew** 2019-12-16 01:18 UTC
Labels: a:enhancement, in:client
