### ISSUE TITLE
[1.12.2] Only allowing topography mapping doesn't map new areas

### ISSUE THREAD

**Issue by xieve** [TeamJM/journeymap#141] opened 2019-08-10 13:11 UTC
#### JourneyMap Version (client & server):

`1.12.2-5.5.5`

#### Forge Version (client & server):

`Example: 1.12.2-14.23.5.2838`

#### Describe the problem in repeatable steps:

1. Open admin settings on a dedicated Forge server (in SP this does not occur)
2. Disallow everything but topography mapping
3. Walk around previously unmapped terrain
4. The areas still aren't being mapped
5. As soon as you enable surface mapping, it works again.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No errors in there.

#### Additional info:

I have also deactivated any radar but that for players. I'm using Journeymap in a modpack and sadly haven't got another server to quickly try without the other mods, but [here](https://gitlab.com/snippets/1883277/)'s the list of mods used. They're all up-to-date.

**Comment by xieve** [comment] 2019-08-10 13:13
I just discovered that it does indeed map the topography for a short period (~1s) after login, but then stops.

**Comment by techbrew-mc** [comment] 2021-02-26 06:53
Couldn't reproduce in 5.7.1b4 on 1.16.4.  Since we're not updating older versions any more, closing this.

**Closed by techbrew-mc** 2021-02-26 06:53 UTC
Labels: a:bug, in:client, jm:5.5.5, mc:1.12.2

**Comment by mysticdrew** [comment] 2021-02-26 15:35
I was able to reproduce it and fixed it for the public release of Journeymap 5.7.1 Beta 4 for mc 1.16. Will be available on curse soonish
