### ISSUE TITLE
Server crash netty spam

### ISSUE THREAD

**Issue by PixelmonPRO** [TeamJM/journeymap#117] opened 2019-06-07 15:28 UTC
#### JourneyMap Version:

`journeymap-1.12.2-5.5.5b7`

#### Forge Version:

`Forge 14.23.5.2809`

#### Describe the problem in repeatable steps:

1. When my server gets high online (100/100), a Netty error occurs: https://gyazo.com/2cface2b01582086344548fc385dac9f

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

https://gist.github.com/PixelmonPRO/4e36ac27850f4f6c59dbeab0c6ad56ca

**Comment by mysticdrew** [comment] 2019-06-17 18:06
This should be fixed in beta 8. I have no way to test on a server that large.  

This issue is caused by a limitation in packet size. With beta 8, Only 10 players are sent per packet instead of all players.

**Closed by mysticdrew** 2019-06-17 18:06 UTC
Labels: a:bug, in:server, jm:5.5.5, mc:1.12.2

**Comment by mysticdrew** [comment] 2019-07-06 18:41
5.5.5 beta 8 is released on curse now. 
https://www.curseforge.com/minecraft/mc-mods/journeymap/files/2736523

I have no way to test such a large server. However the changes to fix this issue will require all clients to update as well. 

This fix was the main update in beta 8. If you could test it out and let me know if it resolved your issue, it would be appreciated, thanks!

**Comment by PixelmonPRO** [comment] 2019-08-06 10:57
@mysticdrew The error is repeated again, journeymap-1.12.2-5.5.5b9 / Forge 14.23.5.2838: https://gist.github.com/PixelmonPRO/53f07a4b47cdea6105ed56cee6c64ab4

**Comment by mysticdrew** [comment] 2019-08-06 14:25
Come into the journeymap discord and put the logs into the #support channel.
