### ISSUE TITLE
Journey map game time is wrong

### ISSUE THREAD

**Issue by Linrox** [TeamJM/journeymap#67] opened 2018-08-26 04:37 UTC
MC Ver:1.12.2
FML: 14.23.4.2705
Mod ver: 1.12.2-5.5.2
Server Used: Spigot 1.12.2 Forge: 14.23.4.2705

This is not a new bug, just one that has not been fixed, but closed.
The game time is incorrect. shows 4pm at noon, ingame.
The only error report i found was on FTB at(https://forum.feed-the-beast.com/threads/journey-maps-clock.264774/#post-1947817) as a closed thread on DEC 2017!!.
I have search github and could not find the any thread on the same issue using the site search options.
![2018-08-26_14 25 03](https://user-images.githubusercontent.com/3826896/44624865-87b9cc80-a93d-11e8-9a0e-9096dfd9d4dd.png)
![2018-08-26_14 28 43](https://user-images.githubusercontent.com/3826896/44624868-90120780-a93d-11e8-8980-5b4e91bde2de.png)

**Comment by kosma** [comment] 2018-11-08 23:20
I think these are not HH:MM, but MM:SS. Minecraft day is 10 minutes long, so a 4 minutes 38 seconds noon would be about right.

**Comment by meradz** [comment] 2018-11-20 18:30
I agree with the above statement in regards to clocks. NOBODY should be required to perform math just to figure out the game time. I would love to see this fixed in a future release. Bonus points for additional option for countdown to sunrise/sunset.

**Comment by kwon0408** [comment] 2019-01-09 15:35
I think it will be better if we can select one from below:

- the current real time clock
  - sunrise at 00:00, noon at 05:00, sunset at 10:00, midnight at 15:00
- Minecraft 24-hour clock
  - sunrise at 06:00, noon at 12:00, sunset at 18:00, midnight at 00:00
- Minecraft tick counter
  - sunrise at 0, noon at 6000, sunset at 12000, midnight at 18000

And I have thought of some more options, allowing to select from:

- Showing sunrise as 0 minutes or 5 minutes, for 20-minute clock
- Showing as e.g. 18:00 or 6:00 PM, for 24-MC-hour clock
- Countdown clock (e.g. noon is shown as 5 minute/6 hour/6000 ticks left until sunset)
- Offsets (similar to real-world time zones)

**Comment by mysticdrew** [comment] 2019-02-18 17:35
This is not a bug, changed to enhancement.

**Comment by MechanosG** [comment] 2019-02-24 20:37
+1 for an option to display 6:00 PM instead of 18:00.  Definitely more aesthetically pleasing for those of us that read clocks as AM/PM in our native country.

**Comment by mysticdrew** [comment] 2019-04-05 22:21
Added two new info slots, GameTime 12hr and GameTime 24hr. 

![](http://puu.sh/DaByy/30efd7009e.png)

**Closed** 2019-04-05 22:22 UTC
Labels: a:enhancement, in:client, jm:5.5.2, mc:1.12.2, status:completed

**Comment by JanSeidlerSF** [comment] 2019-12-12 14:32
This bug is still open, and it is a bug. My MC time displayed on Journeymap is 5 hours ahead of the actual MC time. RFtools screen e.g. shows it correctly on the same server. This IS a bug.

**Comment by mysticdrew** [comment] 2019-12-12 14:39
> This bug is still open, and it is a bug. My MC time displayed on Journeymap is 5 hours ahead of the actual MC time. RFtools screen e.g. shows it correctly on the same server. This IS a bug.

great details...

**Comment by JanSeidlerSF** [comment] 2019-12-12 14:43
Sorry. Standard out-of-the-box installation of All the Mods 3 via Twitch Installer, v5.12.2, based on MC 1.12.2, forge-14.23.5.2838, run on a Nitrado server.

It's seems to be exactly the same problem the op ran into which was turned into a request for more time formats despite him stating that the time displayed on Journeymap is simply off from the actual MC time.

**Comment by mysticdrew** [comment] 2019-12-12 14:45
I dont care about your modpacks or you twitch versions. 
Minecraft Version, Journeymap Version, and forge version are what I need.

**Comment by JanSeidlerSF** [comment] 2019-12-12 14:51
journeymap-1.12.2-5.5.5b9.jar, the other two are in my comment above.

**Comment by mysticdrew** [comment] 2019-12-12 14:52
first, get off the beta version of 5.5.5 and get on the release or the beta of 5.5.6b2

**Comment by JanSeidlerSF** [comment] 2019-12-12 15:09
![image](https://user-images.githubusercontent.com/36708280/70723618-785cbf00-1cf9-11ea-9f47-b3926e71f558.png)

Unfortunately, upgrading client and server to journeymap-1.12.2-5.5.6b2 didn't help. The time the RF screen shows (in this case19:24) is correct when looking at the daynight-cycle, mobspawns, etc.

**Comment by mysticdrew** [comment] 2019-12-12 15:12
Have you tried the other infoslot time types?

**Comment by JanSeidlerSF** [comment] 2019-12-12 15:15
Yes, gametime, "Game Time", "Game Time 12hr" and "Game Time 24hr", the offset remains the same. I also opened a local world and it's the same as on the server.

**Comment by mysticdrew** [comment] 2019-12-12 15:26
It is accurate for me... 
![image](https://user-images.githubusercontent.com/5459941/70725107-65c69380-1cc1-11ea-944f-e8a2b4166ffa.png)

**Comment by JanSeidlerSF** [comment] 2019-12-12 15:31
![image](https://user-images.githubusercontent.com/36708280/70725485-beffe880-1cfc-11ea-8369-695f347661db.png)

So weird, I have no idea where I could check. If it was server-related or something ... *shrug*

**Comment by mysticdrew** [comment] 2019-12-12 15:58
can you do a /time set 0 and take a screenshot for me?
also it may be easier if you come to our discord.

**Comment by mysticdrew** [comment] 2019-12-12 21:16
@JanSeidlerSF 
pop in our discord https://discord.gg/eP8gE69 I may have fixed your issue but I need you to test the new version since I cannot reproduce it.

**Comment by MrOrangeMan** [comment] 2021-11-17 00:42
> It is accurate for me... ![image](https://user-images.githubusercontent.com/5459941/70725107-65c69380-1cc1-11ea-944f-e8a2b4166ffa.png)

That's why it's called a bug

**Comment by sTiKyt** [comment] 2022-09-29 15:20
Hello? This stuff is wrong way around
![image](https://user-images.githubusercontent.com/35602029/193071698-60b66665-d5bd-4331-8db1-e559d9b37af0.png)

It's supposed to be 15:49, not 03:49, and there are no settings to change it

**Comment by mysticdrew** [comment] 2022-09-29 18:14
@sTiKyt your issue is unrelated to this issue. Create a new issue. But there are time format types in the options.
