### ISSUE TITLE
[1.19.2]Confilcts with BBOR (BoundingBoxOutlineReloaded)

### ISSUE THREAD

**Issue by reserveword** [TeamJM/journeymap#529] opened 2022-11-26 14:31 UTC
It won't generate map when loading with bbor
https://github.com/irtimaled/BoundingBoxOutlineReloaded/issues/175
  
#### JourneyMap Version:

journeymap-1.19.2-5.9.0beta3-forge

#### Forge Version:

43.1.57

#### Describe the problem in repeatable steps:

1. install journeymap and [BoundingBoxOutlineReloaded](https://www.curseforge.com/minecraft/mc-mods/bounding-box-outline-reloaded/files/3937162)
2. open minecraft and join a vanilla server
3. map does not generate

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
this line repeating again and again, filling the whole log
[21:22:21] [JM-task-4/WARN] [DataCache] Unexpected error getting ChunkMD from cache: java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / minecraft:worldgen/structure]

**Comment by mysticdrew** [comment] 2022-11-26 14:51
Please provide the full journeymap.log and latest.log files. Attach the files to this issue please.

**Comment by reserveword** [comment] 2022-11-26 14:57
> Please provide the full journeymap.log and latest.log files. Attach the files to this issue please.
most of that log is that line
[journeymap.log.zip](https://github.com/TeamJM/journeymap/files/10096475/journeymap.log.zip)
[2022-11-26-6.log.gz](https://github.com/TeamJM/journeymap/files/10096476/2022-11-26-6.log.gz)

**Comment by mysticdrew** [comment] 2022-12-06 15:11
I am unable to reproduce this with BBOR 2.5.1, I see you were using 2.5.0. Do you still have the issue with 2.5.1?

**Comment by mysticdrew** [comment] 2022-12-06 20:42
This will be fixed in the next release. I'll close and comment when I publish the next release.

**Comment by mysticdrew** [comment] 2022-12-08 15:05
This issue is resolved and in beta for for 1.18.2 and 1.19.3 for both fabric and forge. 
Download here:
https://www.curseforge.com/minecraft/mc-mods/journeymap/files
https://modrinth.com/mod/journeymap/versions

**Closed by mysticdrew** 2022-12-08 15:05 UTC
Labels: a:bug, status:fixed, in:client, status:completed, a:mod-interaction

**Comment by MrFuzzihead** [comment] 2022-12-08 18:49
Just curious if this fix will be pushed to the 1.19.2 version as well! Thank you

**Comment by mysticdrew** [comment] 2022-12-08 20:45
> Just curious if this fix will be pushed to the 1.19.2 version as well! Thank you

as of right now, no with the release of 1.19.3, 1.19.2 is end of life. 
But BBOR will also be issuing a fix on their end.

**Comment by mysticdrew** [comment] 2022-12-08 20:50
Well, maybe I will release a beta4 for 1.19.2

**Comment by mysticdrew** [comment] 2022-12-08 21:05
Ok, beta4 for 1.19.2 is not on modrinth and curseforged(when approved)
