### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Pilad** [TeamJM/journeymap#16] opened 2018-01-03 19:15 UTC
MC 1.10.2 
Forge 12.18.3.2511
journeymap-1.10.2-5.6.0b1

```
java.lang.IllegalArgumentException: name may not be blank
	at journeymap.client.api.model.WaypointBase.setName(WaypointBase.java:117)
	at journeymap.client.ui.waypoint.WaypointEditor.updateWaypointFromForm(WaypointEditor.java:775)
	at journeymap.client.ui.waypoint.WaypointEditor.func_73869_a(WaypointEditor.java:542)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:573)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:527)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by BrainStone** [comment] 2018-01-04 01:01
Duplicate of #14

**Closed by BrainStone** 2018-01-04 01:01 UTC
Labels: a:bug, in:client, jm:5.6.0, mc:1.10.2, status:duplicate
